	/**
	 https://api.flyff.com/image/class/{style}/{fileName}

	 职业
	 初心者:https://api.flyff.com/class/9686

	 圣职者:https://api.flyff.com/class/8962
	 暴力技师:https://api.flyff.com/class/7424
	 守护使者:https://api.flyff.com/class/9389

	 弓箭手:https://api.flyff.com/class/9098
	 暗杀:https://api.flyff.com/class/3545
	 游侠:https://api.flyff.com/class/9295

	 魔导士:https://api.flyff.com/class/9581
	 精神使者:https://api.flyff.com/class/5709
	 元素:https://api.flyff.com/class/9150

	 战士:https://api.flyff.com/class/764
	 刀锋使者:https://api.flyff.com/class/2246
	 骑士:https://api.flyff.com/class/5330

	 //图片地址
	 https://api.flyff.com/image/item/weaswocrystal.png
	 //物品地址
	 https://api.flyff.com/item/14100
	**/

	var pet_lv_item = [
		{"lv":1,"lvStr":"F级","money":"2000000","list":[{"name":1,"probability":1}]},
		{"lv":2,"lvStr":"E级","money":"6200000","list":[{"name":2,"probability":0.3},{"name":1,"probability":0.7}]},
		{"lv":3,"lvStr":"D级","money":"20800000","list":[{"name":3,"probability":0.18},{"name":2,"probability":0.25},{"name":1,"probability":0.57}]},
		{"lv":4,"lvStr":"C级","money":"59550000","list":[{"name":4,"probability":0.06},{"name":3,"probability":0.18},{"name":2,"probability":0.31},{"name":1,"probability":0.45}]},
		{"lv":5,"lvStr":"B级","money":"123800000","list":[{"name":5,"probability":0.04},{"name":4,"probability":0.1},{"name":3,"probability":0.18},{"name":2,"probability":0.28},{"name":1,"probability":0.4}]},
		{"lv":6,"lvStr":"A级","money":"226050000","list":[{"name":7,"probability":0.02},{"name":6,"probability":0.04},{"name":5,"probability":0.07},{"name":4,"probability":0.12},{"name":3,"probability":0.17},{"name":2,"probability":0.23},{"name":1,"probability":0.35}]},
		{"lv":7,"lvStr":"S级","money":"557050000","list":[{"name":9,"probability":0.01},{"name":8,"probability":0.02},{"name":7,"probability":0.04},{"name":6,"probability":0.06},{"name":5,"probability":0.09},{"name":4,"probability":0.13},{"name":3,"probability":0.17},{"name":2,"probability":0.21},{"name":1,"probability":0.27}]},
	]

	var pet_lv_list = [
		{"lv":1,"defense":"6","criticalChance":"1%","criticalDamage":"2%","attribute":"1","attack":"7","hp":"96","list": [{"E": 0.7}, {"D": 0.6}, {"C": 0.5}, {"B": 0.4}, {"A": 0.3}, {"S": 0.2}]},
		{"lv":2,"defense":"12","criticalChance":"2%","criticalDamage":"3%","attribute":"2","attack":"13","hp":"191","list": [{"E": 0.3}, {"D": 0.4}, {"C": 0.5}, {"B": 0.6}, {"A": 0.7}, {"S": 0.8}]},
		{"lv":3,"defense":"24","criticalChance":"3%","criticalDamage":"4%","attribute":"4","attack":"27","hp":"383","list": [{"D": 0.18}, {"C": 0.18}, {"B": 0.25}, {"A": 0.32}, {"S": 0.45}]},
		{"lv":4,"defense":"42","criticalChance":"4%","criticalDamage":"5%","attribute":"7","attack":"47","hp":"670","list": [{"C": 0.06}, {"B": 0.06}, {"A": 0.09}, {"S": 0.15}]},
		{"lv":5,"defense":"66","criticalChance":"5%","criticalDamage":"6%","attribute":"11","attack":"73","hp":"1053","list": [{"B": 0.04}, {"A": 0.06}, {"S": 0.09}]},
		{"lv":6,"defense":"88","criticalChance":"6%","criticalDamage":"7%","attribute":"15","attack":"95","hp":"1356","list": [{"A": 0.04}, {"S": 0.06}]},
		{"lv":7,"defense":"102","criticalChance":"7%","criticalDamage":"9%","attribute":"17","attack":"113","hp":"1628","list": [{"A": 0.02}, {"S": 0.03}]},
		{"lv":8,"defense":"140","criticalChance":"8%","criticalDamage":"11%","attribute":"24","attack":"165","hp":"2539","list": [{"S": 0.02}]},
		{"lv":9,"defense":"198","criticalChance":"9%","criticalDamage":"16%","attribute":"33","attack":"220","hp":"3161","list": [{"S": 0.01}]},
	]

	var incubate_pet = [
		{"name":"狐狸","value":pet_lv_list[0].attribute,"attributeStr":"智力"},
		{"name":"老虎","value":pet_lv_list[0].attribute,"attributeStr":"力量",},
		{"name":"兔子","value":pet_lv_list[0].attribute,"attributeStr":"敏捷",},
		{"name":"狮子","value":pet_lv_list[0].attribute,"attributeStr":"体质",},
		{"name":"飞龙","value":pet_lv_list[0].attack,"attributeStr":"攻击力"},
		{"name":"狮鹫兽","value":pet_lv_list[0].defense,"attributeStr":"防御"},
		{"name":"独角兽","value":pet_lv_list[0].hp,"attributeStr":"hp"},
		{"name":"天使","value":pet_lv_list[0].criticalChance,"attributeStr":"暴击率"},
		{"name":"帝王蟹","value":pet_lv_list[0].criticalDamage,"attributeStr":"暴击伤害"}
	]

	//唤醒百分比范围
	const wakeUpItem = ["5", "7", "9", "11", "13", "15", "17", "19", "21", "23", "25"];

	var data = [
		{
			"name":"珊瑚短剑",
			"id":10319,
			"uid":14437,
			"wikiName":"珊瑚短剑",
			"minAttack":502,
			"maxAttack":504,
			"job":"战士",
			"attackSpeed":"非常快",
			"type":"单手武器",
			"imgUrl":"img/潮汐单手剑.png",
			"description":"在荒野中发现的制作精良的武器。它充满了力量。国人首把卢萨卡武器由小熊工会团队获得",
			"list":[
				{"name":"暴击伤害","min":490,"max":590,fixed:10,cur:"%"},
				{"name":"暴击率","min":200,"max":230,fixed:10,cur:"%"},
				{"name":"攻击速度","min":140,"max":155,fixed:10,cur:"%"},
				{"name":"水炸弹概率","min":4,"max":9,fixed:1,cur:"%"},
			],
			"uList":[
				{"name":"暴击率","min":20,"max":50,fixed:10,cur:"%"},
				{"name":"暴击伤害","min":15,"max":50,fixed:10,cur:"%"},
				{"name":"格挡穿透","min":15,"max":50,fixed:10,cur:"%"},
				{"name":"攻击力","min":2,"max":4,fixed:1,cur:"%"},
				{"name":"生命偷取","min":4,"max":8,fixed:10,cur:"%"},
				{"name":"增加HP","min":2,"max":4,fixed:1,cur:"%"},
				{"name":"力量","min":2,"max":5,fixed:1,cur:""},
				{"name":"体质","min":2,"max":5,fixed:1,cur:""},
				{"name":"敏捷","min":2,"max":5,fixed:1,cur:""},
				{"name":"格挡","min":2,"max":4,fixed:1,cur:"%"},
				{"name":"pve伤害","min":2,"max":4,fixed:1,cur:"%"},
				{"name":"pvp伤害","min":2,"max":4,fixed:1,cur:"%"}
			],
			"wakeUpList":[
				{"name":"毁灭攻击","item": wakeUpItem},{"name":"切裂风轮","item": wakeUpItem},
				{"name":"血之光辉","item": wakeUpItem},{"name":"怒焰回旋","item": wakeUpItem},
				{"name":"爆裂怒击","item": wakeUpItem},{"name":"逆手回旋","item": wakeUpItem},
				{"name":"毁灭狂气","item": wakeUpItem},{"name":"气刃冲击","item": wakeUpItem},
				{"name":"刀剑狂舞","item": wakeUpItem},{"name":"避实就虚","item": wakeUpItem},
				{"name":"裂刃突袭","item": wakeUpItem},{"name":"盾牌猛击","item": wakeUpItem},
				{"name":"狂怒","item": wakeUpItem},{"name":"夜幕降临","item": wakeUpItem},
				{"name":"十字打击","item": wakeUpItem},{"name":"战斧连击","item": wakeUpItem},
			]
		},
		{
			"name":"卢萨卡的水晶剑",
			"id":13257,
			"uid":13556,
			"wikiName":"卢萨卡的水晶剑",
			"minAttack":522,
			"maxAttack":524,
			"job":"战士",
			"attackSpeed":"非常快",
			"type":"单手武器",
			"imgUrl":"img/卢萨卡的水晶剑.png",
			"description":"在荒野中发现的制作精良的武器。它充满了力量。国人首把卢萨卡武器由小熊工会团队获得",
			"list":[
				{"name":"暴击伤害","min":530,"max":630,fixed:10,cur:"%"},
				{"name":"暴击率","min":220,"max":260,fixed:10,cur:"%"},
				{"name":"攻击速度","min":150,"max":165,fixed:10,cur:"%"},
				{"name":"中毒概率","min":4,"max":9,fixed:1,cur:"%"},
			],
			"uList":[
				{"name":"暴击率","min":20,"max":50,fixed:10,cur:"%"},
				{"name":"暴击伤害","min":15,"max":50,fixed:10,cur:"%"},
				{"name":"格挡穿透","min":15,"max":50,fixed:10,cur:"%"},
				{"name":"攻击力","min":2,"max":4,fixed:1,cur:"%"},
				{"name":"生命偷取","min":4,"max":8,fixed:10,cur:"%"},
				{"name":"增加HP","min":2,"max":4,fixed:1,cur:"%"},
				{"name":"力量","min":2,"max":5,fixed:1,cur:""},
				{"name":"体质","min":2,"max":5,fixed:1,cur:""},
				{"name":"敏捷","min":2,"max":5,fixed:1,cur:""},
				{"name":"格挡","min":2,"max":4,fixed:1,cur:"%"},
				{"name":"pve伤害","min":2,"max":4,fixed:1,cur:"%"},
				{"name":"pvp伤害","min":2,"max":4,fixed:1,cur:"%"}
			],
			"wakeUpList":[
				{"name":"毁灭攻击","item": wakeUpItem},{"name":"切裂风轮","item": wakeUpItem},
				{"name":"血之光辉","item": wakeUpItem},{"name":"怒焰回旋","item": wakeUpItem},
				{"name":"爆裂怒击","item": wakeUpItem},{"name":"逆手回旋","item": wakeUpItem},
				{"name":"毁灭狂气","item": wakeUpItem},{"name":"气刃冲击","item": wakeUpItem},
				{"name":"刀剑狂舞","item": wakeUpItem},{"name":"避实就虚","item": wakeUpItem},
				{"name":"裂刃突袭","item": wakeUpItem},{"name":"盾牌猛击","item": wakeUpItem},
				{"name":"狂怒","item": wakeUpItem},{"name":"夜幕降临","item": wakeUpItem},
				{"name":"十字打击","item": wakeUpItem},{"name":"战斧连击","item": wakeUpItem},
			]
		},
		{
			"name":"卢萨卡之剑",
			"id":10906,
			"uid":19508,
			"wikiName":"卢萨卡之剑",
			"minAttack":522,
			"maxAttack":524,
			"job":"战士",
			"attackSpeed":"非常快",
			"type":"单手武器",
			"imgUrl":"img/卢萨卡之剑.png",
			"description":"在荒野中发现的制作精良的武器。它充满了力量。国人首把卢萨卡武器由小熊工会团队获得",
			"list":[
				{"name":"增加HP","min":25,"max":30,fixed:1,cur:"%"},
				{"name":"技能伤害","min":6,"max":7,fixed:1,cur:"%"},
				{"name":"体质","min":25,"max":30,fixed:1,cur:""},
				{"name":"中毒概率","min":4,"max":9,fixed:1,cur:"%"},
			],
			"uList":[
				{"name":"暴击率","min":20,"max":50,fixed:10,cur:"%"},
				{"name":"暴击伤害","min":15,"max":50,fixed:10,cur:"%"},
				{"name":"格挡穿透","min":15,"max":50,fixed:10,cur:"%"},
				{"name":"攻击力","min":2,"max":4,fixed:1,cur:"%"},
				{"name":"生命偷取","min":4,"max":8,fixed:10,cur:"%"},
				{"name":"增加HP","min":2,"max":4,fixed:1,cur:"%"},
				{"name":"力量","min":2,"max":5,fixed:1,cur:""},
				{"name":"体质","min":2,"max":5,fixed:1,cur:""},
				{"name":"敏捷","min":2,"max":5,fixed:1,cur:""},
				{"name":"格挡","min":2,"max":4,fixed:1,cur:"%"},
				{"name":"pve伤害","min":2,"max":4,fixed:1,cur:"%"},
				{"name":"pvp伤害","min":2,"max":4,fixed:1,cur:"%"}
			],
			"wakeUpList":[
				{"name":"毁灭攻击","item": wakeUpItem},{"name":"切裂风轮","item": wakeUpItem},
				{"name":"血之光辉","item": wakeUpItem},{"name":"怒焰回旋","item": wakeUpItem},
				{"name":"爆裂怒击","item": wakeUpItem},{"name":"逆手回旋","item": wakeUpItem},
				{"name":"毁灭狂气","item": wakeUpItem},{"name":"气刃冲击","item": wakeUpItem},
				{"name":"刀剑狂舞","item": wakeUpItem},{"name":"避实就虚","item": wakeUpItem},
				{"name":"裂刃突袭","item": wakeUpItem},{"name":"盾牌猛击","item": wakeUpItem},
				{"name":"狂怒","item": wakeUpItem},{"name":"夜幕降临","item": wakeUpItem},
				{"name":"十字打击","item": wakeUpItem},{"name":"战斧连击","item": wakeUpItem},
			]
		},
		{
			"name":"猛兽",
			"id":13811,
			"uid":19242,
			"wikiName":"猛兽",
			"minAttack":685,
			"maxAttack":694,
			"job":"战士",
			"attackSpeed":"慢",
			"type":"双手武器",
			"imgUrl":"img/潮汐双手剑.png",
			"description":"在荒野中发现的制作精良的武器。它充满了力量。国人首把卢萨卡武器由小熊工会团队获得",
			"list":[
				{"name":"暴击伤害","min":590,"max":690,fixed:10,cur:"%"},
				{"name":"暴击率","min":240,"max":280,fixed:10,cur:"%"},
				{"name":"攻击速度","min":130,"max":150,fixed:10,cur:"%"},
				{"name":"水炸弹概率","min":4,"max":9,fixed:1,cur:"%"},
			],
			"uList":[
				{"name":"暴击伤害","min":30,"max":100,fixed:10,cur:"%"},
				{"name":"格挡穿透","min":30,"max":100,fixed:10,cur:"%"},
				{"name":"暴击率","min":30,"max":100,fixed:10,cur:"%"},
				{"name":"攻击力","min":3,"max":8,fixed:1,cur:"%"},
				{"name":"生命偷取","min":6,"max":15,fixed:10,cur:"%"},
				{"name":"增加HP","min":3,"max":8,fixed:1,cur:"%"},
				{"name":"力量","min":2,"max":10,fixed:1,cur:""},
				{"name":"体质","min":2,"max":10,fixed:1,cur:""},
				{"name":"敏捷","min":2,"max":10,fixed:1,cur:""},
				{"name":"格挡","min":3,"max":8,fixed:1,cur:"%"},
				{"name":"pve伤害","min":3,"max":8,fixed:1,cur:"%"},
				{"name":"pvp伤害","min":3,"max":8,fixed:1,cur:"%"}
			],
			"wakeUpList":[
				{"name":"毁灭攻击","item": wakeUpItem},{"name":"切裂风轮","item": wakeUpItem},
				{"name":"血之光辉","item": wakeUpItem},{"name":"怒焰回旋","item": wakeUpItem},
				{"name":"爆裂怒击","item": wakeUpItem},{"name":"逆手回旋","item": wakeUpItem},
				{"name":"毁灭狂气","item": wakeUpItem},{"name":"碎甲","item": wakeUpItem},
				{"name":"开天辟地","item": wakeUpItem},{"name":"大地共鸣","item": wakeUpItem},
				{"name":"雷霆万钧","item": wakeUpItem},{"name":"极速突刺","item": wakeUpItem},
				{"name":"裂刃突袭","item": wakeUpItem},{"name":"横扫千军","item": wakeUpItem},
			]
		},
		{
			"name":"卢萨卡的水晶巨剑",
			"id":16364,
			"uid":19108,
			"wikiName":"卢萨卡的水晶巨剑",
			"minAttack":705,
			"maxAttack":714,
			"job":"战士",
			"attackSpeed":"慢",
			"type":"双手武器",
			"imgUrl":"img/卢萨卡的水晶巨剑.png",
			"description":"在荒野中发现的制作精良的武器。它充满了力量。国人首把卢萨卡武器由小熊工会团队获得",
			"list":[
				{"name":"暴击伤害","min":620,"max":720,fixed:10,cur:"%"},
				{"name":"暴击率","min":260,"max":300,fixed:10,cur:"%"},
				{"name":"攻击速度","min":140,"max":160,fixed:10,cur:"%"},
				{"name":"流血概率","min":4,"max":9,fixed:1,cur:"%"},
			],
			"uList":[
				{"name":"暴击伤害","min":30,"max":100,fixed:10,cur:"%"},
				{"name":"格挡穿透","min":30,"max":100,fixed:10,cur:"%"},
				{"name":"暴击率","min":30,"max":100,fixed:10,cur:"%"},
				{"name":"攻击力","min":3,"max":8,fixed:1,cur:"%"},
				{"name":"生命偷取","min":6,"max":15,fixed:10,cur:"%"},
				{"name":"增加HP","min":3,"max":8,fixed:1,cur:"%"},
				{"name":"力量","min":2,"max":10,fixed:1,cur:""},
				{"name":"体质","min":2,"max":10,fixed:1,cur:""},
				{"name":"敏捷","min":2,"max":10,fixed:1,cur:""},
				{"name":"格挡","min":3,"max":8,fixed:1,cur:"%"},
				{"name":"pve伤害","min":3,"max":8,fixed:1,cur:"%"},
				{"name":"pvp伤害","min":3,"max":8,fixed:1,cur:"%"}
			],
			"wakeUpList":[
				{"name":"毁灭攻击","item": wakeUpItem},{"name":"切裂风轮","item": wakeUpItem},
				{"name":"血之光辉","item": wakeUpItem},{"name":"怒焰回旋","item": wakeUpItem},
				{"name":"爆裂怒击","item": wakeUpItem},{"name":"逆手回旋","item": wakeUpItem},
				{"name":"毁灭狂气","item": wakeUpItem},{"name":"碎甲","item": wakeUpItem},
				{"name":"开天辟地","item": wakeUpItem},{"name":"大地共鸣","item": wakeUpItem},
				{"name":"雷霆万钧","item": wakeUpItem},{"name":"极速突刺","item": wakeUpItem},
				{"name":"裂刃突袭","item": wakeUpItem},{"name":"横扫千军","item": wakeUpItem},
			]
		},
		{
			"name":"卢萨卡巨剑",
			"id":15489,
			"uid":18025,
			"wikiName":"卢萨卡巨剑",
			"minAttack":705,
			"maxAttack":714,
			"job":"战士",
			"attackSpeed":"慢",
			"type":"双手武器",
			"imgUrl":"img/卢萨卡巨剑.png",
			"description":"在荒野中发现的制作精良的武器。它充满了力量。国人首把卢萨卡武器由小熊工会团队获得",
			"list":[
				{"name":"最大HP","min":28,"max":35,fixed:1,cur:"%"},
				{"name":"体质","min":25,"max":30,fixed:1,cur:""},
				{"name":"格挡","min":8,"max":14,fixed:1,cur:"%"},
				{"name":"击晕概率(PVE)","min":1,"max":3,fixed:1,cur:"%"},
				{"name":"击晕概率(PVP)","min":1,"max":3,fixed:1,cur:"%"},
			],
			"uList":[
				{"name":"暴击伤害","min":30,"max":100,fixed:10,cur:"%"},
				{"name":"格挡穿透","min":30,"max":100,fixed:10,cur:"%"},
				{"name":"暴击率","min":30,"max":100,fixed:10,cur:"%"},
				{"name":"攻击力","min":3,"max":8,fixed:1,cur:"%"},
				{"name":"生命偷取","min":6,"max":15,fixed:10,cur:"%"},
				{"name":"增加HP","min":3,"max":8,fixed:1,cur:"%"},
				{"name":"力量","min":2,"max":10,fixed:1,cur:""},
				{"name":"体质","min":2,"max":10,fixed:1,cur:""},
				{"name":"敏捷","min":2,"max":10,fixed:1,cur:""},
				{"name":"格挡","min":3,"max":8,fixed:1,cur:"%"},
				{"name":"pve伤害","min":3,"max":8,fixed:1,cur:"%"},
				{"name":"pvp伤害","min":3,"max":8,fixed:1,cur:"%"}
			],
			"wakeUpList":[
				{"name":"毁灭攻击","item": wakeUpItem},{"name":"切裂风轮","item": wakeUpItem},
				{"name":"血之光辉","item": wakeUpItem},{"name":"怒焰回旋","item": wakeUpItem},
				{"name":"爆裂怒击","item": wakeUpItem},{"name":"逆手回旋","item": wakeUpItem},
				{"name":"毁灭狂气","item": wakeUpItem},{"name":"碎甲","item": wakeUpItem},
				{"name":"开天辟地","item": wakeUpItem},{"name":"大地共鸣","item": wakeUpItem},
				{"name":"雷霆万钧","item": wakeUpItem},{"name":"极速突刺","item": wakeUpItem},
				{"name":"裂刃突袭","item": wakeUpItem},{"name":"横扫千军","item": wakeUpItem},
			]
		},
		{
			"name":"螺号",
			"id":19897,
			"uid":11957,
			"wikiName":"螺号",
			"minAttack":524,
			"maxAttack":526,
			"job":"战士",
			"attackSpeed":"通用",
			"type":"单手武器",
			"imgUrl":"img/潮汐单手斧.png",
			"description":"在荒野中发现的制作精良的武器。它充满了力量。国人首把卢萨卡武器由小熊工会团队获得",
			"list":[
				{"name":"暴击伤害","min":530,"max":630,fixed:10,cur:"%"},
				{"name":"暴击率","min":160,"max":200,fixed:10,cur:"%"},
				{"name":"攻击速度","min":100,"max":115,fixed:10,cur:"%"},
				{"name":"水炸弹概率","min":4,"max":9,fixed:1,cur:"%"},
			],
			"uList":[
				{"name":"暴击率","min":20,"max":50,fixed:10,cur:"%"},
				{"name":"暴击伤害","min":15,"max":50,fixed:10,cur:"%"},
				{"name":"格挡穿透","min":15,"max":50,fixed:10,cur:"%"},
				{"name":"攻击力","min":2,"max":4,fixed:1,cur:"%"},
				{"name":"生命偷取","min":4,"max":8,fixed:10,cur:"%"},
				{"name":"增加HP","min":2,"max":4,fixed:1,cur:"%"},
				{"name":"力量","min":2,"max":5,fixed:1,cur:""},
				{"name":"体质","min":2,"max":5,fixed:1,cur:""},
				{"name":"敏捷","min":2,"max":5,fixed:1,cur:""},
				{"name":"格挡","min":20,"max":40,fixed:10,cur:"%"},
				{"name":"pve伤害","min":2,"max":4,fixed:1,cur:"%"},
				{"name":"pvp伤害","min":2,"max":4,fixed:1,cur:"%"}
			],
			"wakeUpList":[
				{"name":"毁灭攻击","item": wakeUpItem},{"name":"切裂风轮","item": wakeUpItem},
				{"name":"血之光辉","item": wakeUpItem},{"name":"怒焰回旋","item": wakeUpItem},
				{"name":"爆裂怒击","item": wakeUpItem},{"name":"逆手回旋","item": wakeUpItem},
				{"name":"毁灭狂气","item": wakeUpItem},{"name":"气刃冲击","item": wakeUpItem},
				{"name":"刀剑狂舞","item": wakeUpItem},{"name":"避实就虚","item": wakeUpItem},
				{"name":"裂刃突袭","item": wakeUpItem},{"name":"盾牌猛击","item": wakeUpItem},
				{"name":"狂怒","item": wakeUpItem},{"name":"夜幕降临","item": wakeUpItem},
				{"name":"十字打击","item": wakeUpItem},{"name":"战斧连击","item": wakeUpItem}
			]
		},
		{
			"name":"卢萨卡的水晶斧",
			"id":15714,
			"uid":16171,
			"wikiName":"卢萨卡的水晶斧",
			"minAttack":544,
			"maxAttack":546,
			"job":"战士",
			"attackSpeed":"通用",
			"type":"单手武器",
			"imgUrl":"img/卢萨卡的水晶斧.png",
			"description":"在荒野中发现的制作精良的武器。它充满了力量。国人首把卢萨卡武器由小熊工会团队获得",
			"list":[
				{"name":"暴击伤害","min":550,"max":650,fixed:10,cur:"%"},
				{"name":"暴击率","min":180,"max":220,fixed:10,cur:"%"},
				{"name":"攻击速度","min":110,"max":130,fixed:10,cur:"%"},
				{"name":"流血概率","min":4,"max":9,fixed:1,cur:"%"},
			],
			"uList":[
				{"name":"暴击率","min":20,"max":50,fixed:10,cur:"%"},
				{"name":"暴击伤害","min":15,"max":50,fixed:10,cur:"%"},
				{"name":"格挡穿透","min":15,"max":50,fixed:10,cur:"%"},
				{"name":"攻击力","min":2,"max":4,fixed:1,cur:"%"},
				{"name":"生命偷取","min":4,"max":8,fixed:10,cur:"%"},
				{"name":"增加HP","min":2,"max":4,fixed:1,cur:"%"},
				{"name":"力量","min":2,"max":5,fixed:1,cur:""},
				{"name":"体质","min":2,"max":5,fixed:1,cur:""},
				{"name":"敏捷","min":2,"max":5,fixed:1,cur:""},
				{"name":"格挡","min":20,"max":40,fixed:10,cur:"%"},
				{"name":"pve伤害","min":2,"max":4,fixed:1,cur:"%"},
				{"name":"pvp伤害","min":2,"max":4,fixed:1,cur:"%"}
			],
			"wakeUpList":[
				{"name":"毁灭攻击","item": wakeUpItem},{"name":"切裂风轮","item": wakeUpItem},
				{"name":"血之光辉","item": wakeUpItem},{"name":"怒焰回旋","item": wakeUpItem},
				{"name":"爆裂怒击","item": wakeUpItem},{"name":"逆手回旋","item": wakeUpItem},
				{"name":"毁灭狂气","item": wakeUpItem},{"name":"气刃冲击","item": wakeUpItem},
				{"name":"刀剑狂舞","item": wakeUpItem},{"name":"避实就虚","item": wakeUpItem},
				{"name":"裂刃突袭","item": wakeUpItem},{"name":"盾牌猛击","item": wakeUpItem},
				{"name":"狂怒","item": wakeUpItem},{"name":"夜幕降临","item": wakeUpItem},
				{"name":"十字打击","item": wakeUpItem},{"name":"战斧连击","item": wakeUpItem}
			]
		},
		{
			"name":"卢萨卡之斧",
			"id":10720,
			"uid":16721,
			"wikiName":"卢萨卡之斧",
			"minAttack":544,
			"maxAttack":546,
			"job":"战士",
			"attackSpeed":"通用",
			"type":"单手武器",
			"imgUrl":"img/卢萨卡之斧.png",
			"description":"在荒野中发现的制作精良的武器。它充满了力量。国人首把卢萨卡武器由小熊工会团队获得",
			"list":[
				{"name":"最大HP","min":20,"max":25,fixed:1,cur:"%"},
				{"name":"技能伤害","min":6,"max":8,fixed:1,cur:"%"},
				{"name":"承受伤害","min":4,"max":7,fixed:1,cur:"%"},
				{"name":"流血概率","min":4,"max":9,fixed:1,cur:"%"},
			],
			"uList":[
				{"name":"暴击率","min":20,"max":50,fixed:10,cur:"%"},
				{"name":"暴击伤害","min":15,"max":50,fixed:10,cur:"%"},
				{"name":"格挡穿透","min":15,"max":50,fixed:10,cur:"%"},
				{"name":"攻击力","min":2,"max":4,fixed:1,cur:"%"},
				{"name":"生命偷取","min":4,"max":8,fixed:10,cur:"%"},
				{"name":"增加HP","min":2,"max":4,fixed:1,cur:"%"},
				{"name":"力量","min":2,"max":5,fixed:1,cur:""},
				{"name":"体质","min":2,"max":5,fixed:1,cur:""},
				{"name":"敏捷","min":2,"max":5,fixed:1,cur:""},
				{"name":"格挡","min":20,"max":40,fixed:10,cur:"%"},
				{"name":"pve伤害","min":2,"max":4,fixed:1,cur:"%"},
				{"name":"pvp伤害","min":2,"max":4,fixed:1,cur:"%"}
			],
			"wakeUpList":[
				{"name":"毁灭攻击","item": wakeUpItem},{"name":"切裂风轮","item": wakeUpItem},
				{"name":"血之光辉","item": wakeUpItem},{"name":"怒焰回旋","item": wakeUpItem},
				{"name":"爆裂怒击","item": wakeUpItem},{"name":"逆手回旋","item": wakeUpItem},
				{"name":"毁灭狂气","item": wakeUpItem},{"name":"气刃冲击","item": wakeUpItem},
				{"name":"刀剑狂舞","item": wakeUpItem},{"name":"避实就虚","item": wakeUpItem},
				{"name":"裂刃突袭","item": wakeUpItem},{"name":"盾牌猛击","item": wakeUpItem},
				{"name":"狂怒","item": wakeUpItem},{"name":"夜幕降临","item": wakeUpItem},
				{"name":"十字打击","item": wakeUpItem},{"name":"战斧连击","item": wakeUpItem}
			]
		},
		{
			"name":"绝渊",
			"id":14402,
			"uid":11855,
			"wikiName":"绝渊",
			"minAttack":685,
			"maxAttack":694,
			"job":"战士",
			"attackSpeed":"非常慢",
			"type":"双手武器",
			"imgUrl":"img/潮汐双手斧.png",
			"description":"在荒野中发现的制作精良的武器。它充满了力量。国人首把卢萨卡武器由小熊工会团队获得",
			"list":[
				{"name":"暴击伤害","min":520,"max":620,fixed:10,cur:"%"},
				{"name":"暴击率","min":310,"max":340,fixed:10,cur:"%"},
				{"name":"攻击速度","min":80,"max":95,fixed:10,cur:"%"},
				{"name":"水炸弹概率","min":4,"max":9,fixed:1,cur:"%"},
			],
			"uList":[
				{"name":"暴击伤害","min":30,"max":100,fixed:10,cur:"%"},
				{"name":"格挡穿透","min":30,"max":100,fixed:10,cur:"%"},
				{"name":"暴击率","min":30,"max":100,fixed:10,cur:"%"},
				{"name":"攻击力","min":3,"max":8,fixed:1,cur:"%"},
				{"name":"生命偷取","min":6,"max":15,fixed:10,cur:"%"},
				{"name":"增加HP","min":3,"max":8,fixed:1,cur:"%"},
				{"name":"力量","min":2,"max":10,fixed:1,cur:""},
				{"name":"体质","min":2,"max":10,fixed:1,cur:""},
				{"name":"敏捷","min":2,"max":10,fixed:1,cur:""},
				{"name":"格挡","min":3,"max":8,fixed:1,cur:"%"},
				{"name":"pve伤害","min":3,"max":8,fixed:1,cur:"%"},
				{"name":"pvp伤害","min":3,"max":8,fixed:1,cur:"%"}
			],
			"wakeUpList":[
				{"name":"毁灭攻击","item": wakeUpItem},{"name":"切裂风轮","item": wakeUpItem},
				{"name":"血之光辉","item": wakeUpItem},{"name":"怒焰回旋","item": wakeUpItem},
				{"name":"爆裂怒击","item": wakeUpItem},{"name":"逆手回旋","item": wakeUpItem},
				{"name":"毁灭狂气","item": wakeUpItem},{"name":"碎甲","item": wakeUpItem},
				{"name":"开天辟地","item": wakeUpItem},{"name":"大地共鸣","item": wakeUpItem},
				{"name":"雷霆万钧","item": wakeUpItem},{"name":"极速突刺","item": wakeUpItem},
				{"name":"裂刃突袭","item": wakeUpItem},{"name":"横扫千军","item": wakeUpItem},
			]
		},
		{
			"name":"卢萨卡的水晶巨斧",
			"id":16147,
			"uid":17978,
			"wikiName":"卢萨卡的水晶巨斧",
			"minAttack":705,
			"maxAttack":714,
			"job":"战士",
			"attackSpeed":"非常慢",
			"type":"双手武器",
			"imgUrl":"img/卢萨卡的水晶巨斧.png",
			"description":"在荒野中发现的制作精良的武器。它充满了力量。国人首把卢萨卡武器由小熊工会团队获得",
			"list":[
				{"name":"暴击伤害","min":550,"max":650,fixed:10,cur:"%"},
				{"name":"暴击率","min":320,"max":360,fixed:10,cur:"%"},
				{"name":"攻击速度","min":90,"max":110,fixed:10,cur:"%"},
				{"name":"击晕概率(PVE)","min":1,"max":3,fixed:1,cur:"%"},
				{"name":"击晕概率(PVP)","min":1,"max":3,fixed:1,cur:"%"},
			],
			"uList":[
				{"name":"暴击伤害","min":30,"max":100,fixed:10,cur:"%"},
				{"name":"格挡穿透","min":30,"max":100,fixed:10,cur:"%"},
				{"name":"暴击率","min":30,"max":100,fixed:10,cur:"%"},
				{"name":"攻击力","min":3,"max":8,fixed:1,cur:"%"},
				{"name":"生命偷取","min":6,"max":15,fixed:10,cur:"%"},
				{"name":"增加HP","min":3,"max":8,fixed:1,cur:"%"},
				{"name":"力量","min":2,"max":10,fixed:1,cur:""},
				{"name":"体质","min":2,"max":10,fixed:1,cur:""},
				{"name":"敏捷","min":2,"max":10,fixed:1,cur:""},
				{"name":"格挡","min":3,"max":8,fixed:1,cur:"%"},
				{"name":"pve伤害","min":3,"max":8,fixed:1,cur:"%"},
				{"name":"pvp伤害","min":3,"max":8,fixed:1,cur:"%"}
			],
			"wakeUpList":[
				{"name":"毁灭攻击","item": wakeUpItem},{"name":"切裂风轮","item": wakeUpItem},
				{"name":"血之光辉","item": wakeUpItem},{"name":"怒焰回旋","item": wakeUpItem},
				{"name":"爆裂怒击","item": wakeUpItem},{"name":"逆手回旋","item": wakeUpItem},
				{"name":"毁灭狂气","item": wakeUpItem},{"name":"碎甲","item": wakeUpItem},
				{"name":"开天辟地","item": wakeUpItem},{"name":"大地共鸣","item": wakeUpItem},
				{"name":"雷霆万钧","item": wakeUpItem},{"name":"极速突刺","item": wakeUpItem},
				{"name":"裂刃突袭","item": wakeUpItem},{"name":"横扫千军","item": wakeUpItem},
			]
		},
		{
			"name":"卢萨卡巨斧",
			"id":11510,
			"uid":14844,
			"wikiName":"卢萨卡巨斧",
			"minAttack":685,
			"maxAttack":694,
			"job":"战士",
			"attackSpeed":"非常慢",
			"type":"双手武器",
			"imgUrl":"img/卢萨卡巨斧.png",
			"description":"在荒野中发现的制作精良的武器。它充满了力量。国人首把卢萨卡武器由小熊工会团队获得",
			"list":[
				{"name":"最大HP","min":28,"max":35,fixed:1,cur:"%"},
				{"name":"体质","min":25,"max":30,fixed:1,cur:""},
				{"name":"承受伤害","min":6,"max":10,fixed:1,cur:"%"},
				{"name":"击晕概率(PVE)","min":1,"max":3,fixed:1,cur:"%"},
				{"name":"击晕概率(PVP)","min":1,"max":3,fixed:1,cur:"%"},
			],
			"uList":[
				{"name":"暴击伤害","min":30,"max":100,fixed:10,cur:"%"},
				{"name":"格挡穿透","min":30,"max":100,fixed:10,cur:"%"},
				{"name":"暴击率","min":30,"max":100,fixed:10,cur:"%"},
				{"name":"攻击力","min":3,"max":8,fixed:1,cur:"%"},
				{"name":"生命偷取","min":6,"max":15,fixed:10,cur:"%"},
				{"name":"增加HP","min":3,"max":8,fixed:1,cur:"%"},
				{"name":"力量","min":2,"max":10,fixed:1,cur:""},
				{"name":"体质","min":2,"max":10,fixed:1,cur:""},
				{"name":"敏捷","min":2,"max":10,fixed:1,cur:""},
				{"name":"格挡","min":3,"max":8,fixed:1,cur:"%"},
				{"name":"pve伤害","min":3,"max":8,fixed:1,cur:"%"},
				{"name":"pvp伤害","min":3,"max":8,fixed:1,cur:"%"}
			],
			"wakeUpList":[
				{"name":"毁灭攻击","item": wakeUpItem},{"name":"切裂风轮","item": wakeUpItem},
				{"name":"血之光辉","item": wakeUpItem},{"name":"怒焰回旋","item": wakeUpItem},
				{"name":"爆裂怒击","item": wakeUpItem},{"name":"逆手回旋","item": wakeUpItem},
				{"name":"毁灭狂气","item": wakeUpItem},{"name":"碎甲","item": wakeUpItem},
				{"name":"开天辟地","item": wakeUpItem},{"name":"大地共鸣","item": wakeUpItem},
				{"name":"雷霆万钧","item": wakeUpItem},{"name":"极速突刺","item": wakeUpItem},
				{"name":"裂刃突袭","item": wakeUpItem},{"name":"横扫千军","item": wakeUpItem},
			]
		},
		{
			"name":"涡旋",
			"id":13024,
			"uid":15191,
			"wikiName":"涡旋",
			"minAttack":456,
			"maxAttack":458,
			"job":"弓箭手",
			"attackSpeed":"快速",
			"type":"双手武器",
			"imgUrl":"img/潮汐溜溜球.png",
			"description":"在荒野中发现的制作精良的武器。它充满了力量。国人首把卢萨卡武器由小熊工会团队获得",
			"list":[
				{"name":"暴击伤害","min":540,"max":640,fixed:10,cur:"%"},
				{"name":"力量","min":23,"max":28,fixed:1,cur:""},
				{"name":"暴击率","min":160,"max":230,fixed:10,cur:"%"},
				{"name":"水炸弹概率","min":4,"max":9,fixed:1,cur:"%"},
			],
			"uList":[
				{"name":"暴击伤害","min":30,"max":100,fixed:10,cur:"%"},
				{"name":"格挡穿透","min":30,"max":100,fixed:10,cur:"%"},
				{"name":"暴击率","min":30,"max":100,fixed:10,cur:"%"},
				{"name":"攻击力","min":3,"max":8,fixed:1,cur:"%"},
				{"name":"生命偷取","min":6,"max":15,fixed:10,cur:"%"},
				{"name":"增加HP","min":3,"max":8,fixed:1,cur:"%"},
				{"name":"力量","min":2,"max":10,fixed:1,cur:""},
				{"name":"体质","min":2,"max":10,fixed:1,cur:""},
				{"name":"敏捷","min":2,"max":10,fixed:1,cur:""},
				{"name":"格挡","min":3,"max":8,fixed:1,cur:"%"},
				{"name":"pve伤害","min":3,"max":8,fixed:1,cur:"%"},
				{"name":"pvp伤害","min":3,"max":8,fixed:1,cur:"%"},
				{"name":"移动速度","min":2,"max":10,fixed:1,cur:"%"}
			],
			"wakeUpList":[
				{"name":"死亡轮舞","item": wakeUpItem},{"name":"偷袭","item": wakeUpItem},
				{"name":"十字震荡","item": wakeUpItem},{"name":"迟缓术","item": wakeUpItem},
				{"name":"死亡爆破","item": wakeUpItem},{"name":"背后突袭","item": wakeUpItem},
				{"name":"乾坤一掷","item": ["2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12"]},
				{"name":"毒箭","item": wakeUpItem},
			]
		},
		{
			"name":"卢萨卡的水晶飞轮",
			"id":12362,
			"uid":15533,
			"wikiName":"卢萨卡的水晶飞轮",
			"minAttack":476,
			"maxAttack":478,
			"job":"弓箭手",
			"attackSpeed":"快速",
			"type":"双手武器",
			"imgUrl":"img/卢萨卡的水晶飞轮.png",
			"description":"在荒野中发现的制作精良的武器。它充满了力量。国人首把卢萨卡武器由小熊工会团队获得",
			"list":[
				{"name":"暴击伤害","min":570,"max":670,fixed:10,cur:"%"},
				{"name":"力量","min":25,"max":30,fixed:1,cur:""},
				{"name":"暴击率","min":180,"max":250,fixed:10,cur:"%"},
				{"name":"流血概率","min":4,"max":9,fixed:1,cur:"%"},
			],
			"uList":[
				{"name":"暴击伤害","min":30,"max":100,fixed:10,cur:"%"},
				{"name":"格挡穿透","min":30,"max":100,fixed:10,cur:"%"},
				{"name":"暴击率","min":30,"max":100,fixed:10,cur:"%"},
				{"name":"攻击力","min":3,"max":8,fixed:1,cur:"%"},
				{"name":"生命偷取","min":6,"max":15,fixed:10,cur:"%"},
				{"name":"增加HP","min":3,"max":8,fixed:1,cur:"%"},
				{"name":"力量","min":2,"max":10,fixed:1,cur:""},
				{"name":"体质","min":2,"max":10,fixed:1,cur:""},
				{"name":"敏捷","min":2,"max":10,fixed:1,cur:""},
				{"name":"格挡","min":3,"max":8,fixed:1,cur:"%"},
				{"name":"pve伤害","min":3,"max":8,fixed:1,cur:"%"},
				{"name":"pvp伤害","min":3,"max":8,fixed:1,cur:"%"},
				{"name":"移动速度","min":2,"max":10,fixed:1,cur:"%"}
			],
			"wakeUpList":[
				{"name":"死亡轮舞","item": wakeUpItem},{"name":"偷袭","item": wakeUpItem},
				{"name":"十字震荡","item": wakeUpItem},{"name":"迟缓术","item": wakeUpItem},
				{"name":"死亡爆破","item": wakeUpItem},{"name":"背后突袭","item": wakeUpItem},
				{"name":"乾坤一掷","item": ["2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12"]},
				{"name":"毒箭","item": wakeUpItem},
			]
		},
		{
			"name":"卢萨卡飞轮",
			"id":18102,
			"uid":18619,
			"wikiName":"卢萨卡飞轮",
			"minAttack":456,
			"maxAttack":458,
			"job":"弓箭手",
			"attackSpeed":"快速",
			"type":"双手武器",
			"imgUrl":"img/卢萨卡飞轮.png",
			"description":"在荒野中发现的制作精良的武器。它充满了力量。国人首把卢萨卡武器由小熊工会团队获得",
			"list":[
				{"name":"最大HP","min":25,"max":30,fixed:1,cur:"%"},
				{"name":"体质","min":25,"max":30,fixed:1,cur:""},
				{"name":"承受伤害","min":6,"max":10,fixed:1,cur:"%"},
				{"name":"减速概率","min":4,"max":9,fixed:1,cur:"%"},
			],
			"uList":[
				{"name":"暴击伤害","min":30,"max":100,fixed:10,cur:"%"},
				{"name":"格挡穿透","min":30,"max":100,fixed:10,cur:"%"},
				{"name":"暴击率","min":30,"max":100,fixed:10,cur:"%"},
				{"name":"攻击力","min":3,"max":8,fixed:1,cur:"%"},
				{"name":"生命偷取","min":6,"max":15,fixed:10,cur:"%"},
				{"name":"增加HP","min":3,"max":8,fixed:1,cur:"%"},
				{"name":"力量","min":2,"max":10,fixed:1,cur:""},
				{"name":"体质","min":2,"max":10,fixed:1,cur:""},
				{"name":"敏捷","min":2,"max":10,fixed:1,cur:""},
				{"name":"格挡","min":3,"max":8,fixed:1,cur:"%"},
				{"name":"pve伤害","min":3,"max":8,fixed:1,cur:"%"},
				{"name":"pvp伤害","min":3,"max":8,fixed:1,cur:"%"},
				{"name":"移动速度","min":2,"max":10,fixed:1,cur:"%"}
			],
			"wakeUpList":[
				{"name":"死亡轮舞","item": wakeUpItem},{"name":"偷袭","item": wakeUpItem},
				{"name":"十字震荡","item": wakeUpItem},{"name":"迟缓术","item": wakeUpItem},
				{"name":"死亡爆破","item": wakeUpItem},{"name":"背后突袭","item": wakeUpItem},
				{"name":"乾坤一掷","item": ["2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12"]},
				{"name":"毒箭","item": wakeUpItem},
			]
		},
		{
			"name":"怒涛",
			"id":16014,
			"uid":13529,
			"wikiName":"怒涛",
			"minAttack":511,
			"maxAttack":512,
			"job":"弓箭手",
			"attackSpeed":"快速",
			"type":"双手武器",
			"imgUrl":"img/潮汐弓.png",
			"description":"在荒野中发现的制作精良的武器。它充满了力量。国人首把卢萨卡武器由小熊工会团队获得",
			"list":[
				{"name":"暴击伤害","min":550,"max":650,fixed:10,cur:"%"},
				{"name":"攻击力","min":10,"max":15,fixed:1,cur:"%"},
				{"name":"暴击率","min":15,"max":20,fixed:10,cur:"%"},
				{"name":"水炸弹概率","min":5,"max":9,fixed:1,cur:"%"},
			],
			"uList":[
				{"name":"暴击伤害","min":30,"max":100,fixed:10,cur:"%"},
				{"name":"格挡穿透","min":30,"max":100,fixed:10,cur:"%"},
				{"name":"暴击率","min":30,"max":100,fixed:10,cur:"%"},
				{"name":"攻击力","min":3,"max":8,fixed:1,cur:"%"},
				{"name":"生命偷取","min":6,"max":15,fixed:10,cur:"%"},
				{"name":"增加HP","min":3,"max":8,fixed:1,cur:"%"},
				{"name":"力量","min":2,"max":10,fixed:1,cur:""},
				{"name":"体质","min":2,"max":10,fixed:1,cur:""},
				{"name":"敏捷","min":2,"max":10,fixed:1,cur:""},
				{"name":"格挡","min":3,"max":8,fixed:1,cur:"%"},
				{"name":"pve伤害","min":3,"max":8,fixed:1,cur:"%"},
				{"name":"pvp伤害","min":3,"max":8,fixed:1,cur:"%"},
			],
			"wakeUpList":[
				{"name": "箭雨", "item": wakeUpItem},{"name": "自动射击", "item": wakeUpItem},
				{"name": "三连强射", "item": wakeUpItem},{"name": "精准射击", "item": wakeUpItem},
				{"name": "伏击", "item": wakeUpItem},{"name": "冰箭", "item": wakeUpItem},
				{"name": "火焰箭矢", "item": wakeUpItem},{"name": "毒箭", "item": wakeUpItem},
				{"name": "沉默之箭", "item": wakeUpItem},{"name": "乱箭射击", "item": wakeUpItem},
				{"name": "穿透箭", "item": wakeUpItem},
			]
		},
		{
			"name":"卢萨卡的水晶弓",
			"id":11905,
			"uid":18425,
			"wikiName":"卢萨卡的水晶弓",
			"minAttack":531,
			"maxAttack":532,
			"job":"弓箭手",
			"attackSpeed":"快速",
			"type":"双手武器",
			"imgUrl":"img/卢萨卡的水晶弓.png",
			"description":"在荒野中发现的制作精良的武器。它充满了力量。国人首把卢萨卡武器由小熊工会团队获得",
			"list":[
				{"name":"暴击伤害","min":580,"max":680,fixed:10,cur:"%"},
				{"name":"攻击力","min":12,"max":17,fixed:1,cur:"%"},
				{"name":"暴击率","min":18,"max":22,fixed:10,cur:"%"},
				{"name":"中毒概率","min":5,"max":9,fixed:1,cur:"%"},
			],
			"uList":[
				{"name":"暴击伤害","min":30,"max":100,fixed:10,cur:"%"},
				{"name":"格挡穿透","min":30,"max":100,fixed:10,cur:"%"},
				{"name":"暴击率","min":30,"max":100,fixed:10,cur:"%"},
				{"name":"攻击力","min":3,"max":8,fixed:1,cur:"%"},
				{"name":"生命偷取","min":6,"max":15,fixed:10,cur:"%"},
				{"name":"增加HP","min":3,"max":8,fixed:1,cur:"%"},
				{"name":"力量","min":2,"max":10,fixed:1,cur:""},
				{"name":"体质","min":2,"max":10,fixed:1,cur:""},
				{"name":"敏捷","min":2,"max":10,fixed:1,cur:""},
				{"name":"格挡","min":3,"max":8,fixed:1,cur:"%"},
				{"name":"pve伤害","min":3,"max":8,fixed:1,cur:"%"},
				{"name":"pvp伤害","min":3,"max":8,fixed:1,cur:"%"},
			],
			"wakeUpList":[
				{"name": "箭雨", "item": wakeUpItem},{"name": "自动射击", "item": wakeUpItem},
				{"name": "三连强射", "item": wakeUpItem},{"name": "精准射击", "item": wakeUpItem},
				{"name": "伏击", "item": wakeUpItem},{"name": "冰箭", "item": wakeUpItem},
				{"name": "火焰箭矢", "item": wakeUpItem},{"name": "毒箭", "item": wakeUpItem},
				{"name": "沉默之箭", "item": wakeUpItem},{"name": "乱箭射击", "item": wakeUpItem},
				{"name": "穿透箭", "item": wakeUpItem},
			]
		},
		{
			"name":"卢萨卡之弓",
			"id":11095,
			"uid":17909,
			"wikiName":"卢萨卡之弓",
			"minAttack":531,
			"maxAttack":532,
			"job":"弓箭手",
			"attackSpeed":"快速",
			"type":"双手武器",
			"imgUrl":"img/卢萨卡之弓.png",
			"description":"在荒野中发现的制作精良的武器。它充满了力量。国人首把卢萨卡武器由小熊工会团队获得",
			"list":[
				{"name":"最大HP","min":25,"max":30,fixed:1,cur:"%"},
				{"name":"体质","min":25,"max":30,fixed:1,cur:""},
				{"name":"承受伤害","min":6,"max":10,fixed:1,cur:"%"},
				{"name":"中毒概率","min":4,"max":9,fixed:1,cur:"%"},
			],
			"uList":[
				{"name":"暴击伤害","min":30,"max":100,fixed:10,cur:"%"},
				{"name":"格挡穿透","min":30,"max":100,fixed:10,cur:"%"},
				{"name":"暴击率","min":30,"max":100,fixed:10,cur:"%"},
				{"name":"攻击力","min":3,"max":8,fixed:1,cur:"%"},
				{"name":"生命偷取","min":6,"max":15,fixed:10,cur:"%"},
				{"name":"增加HP","min":3,"max":8,fixed:1,cur:"%"},
				{"name":"力量","min":2,"max":10,fixed:1,cur:""},
				{"name":"体质","min":2,"max":10,fixed:1,cur:""},
				{"name":"敏捷","min":2,"max":10,fixed:1,cur:""},
				{"name":"格挡","min":3,"max":8,fixed:1,cur:"%"},
				{"name":"pve伤害","min":3,"max":8,fixed:1,cur:"%"},
				{"name":"pvp伤害","min":3,"max":8,fixed:1,cur:"%"},
			],
			"wakeUpList":[
				{"name": "箭雨", "item": wakeUpItem},{"name": "自动射击", "item": wakeUpItem},
				{"name": "三连强射", "item": wakeUpItem},{"name": "精准射击", "item": wakeUpItem},
				{"name": "伏击", "item": wakeUpItem},{"name": "冰箭", "item": wakeUpItem},
				{"name": "火焰箭矢", "item": wakeUpItem},{"name": "毒箭", "item": wakeUpItem},
				{"name": "沉默之箭", "item": wakeUpItem},{"name": "乱箭射击", "item": wakeUpItem},
				{"name": "穿透箭", "item": wakeUpItem},
			]
		},
		{
			"name":"海潮回响",
			"id":15914,
			"uid":14000,
			"wikiName":"海潮回响",
			"minAttack":567,
			"maxAttack":570,
			"job":"魔导士",
			"attackSpeed":"慢",
			"type":"双手武器",
			"imgUrl":"img/潮汐法杖.png",
			"description":"在荒野中发现的制作精良的武器。它充满了力量。国人首把卢萨卡武器由小熊工会团队获得",
			"list":[
				{"name":"全元素精通","min":18,"max":23,fixed:1,cur:"%"},
				{"name":"释法速度","min":26,"max":30,fixed:1,cur:"%"},
				{"name":"智力","min":22,"max":28,cur:""},
				{"name":"水炸弹概率","min":4,"max":9,fixed:1,cur:"%"},
			],
			"uList":[
				{"name":"攻击力","min":3,"max":8,fixed:1,cur:"%"},
				{"name":"生命偷取","min":6,"max":15,fixed:10,cur:"%"},
				{"name":"增加HP","min":3,"max":8,fixed:1,cur:"%"},
				{"name":"体质","min":2,"max":10,fixed:1,cur:""},
				{"name":"智力","min":2,"max":10,fixed:1,cur:""},
				{"name":"格挡","min":3,"max":8,fixed:1,cur:"%"},
				{"name":"pve伤害","min":3,"max":8,fixed:1,cur:"%"},
				{"name":"pvp伤害","min":3,"max":8,fixed:1,cur:"%"},
				{"name":"释法速度","min":3,"max":10,fixed:1,cur:"%"},
				{"name":"全元素精通","min":3,"max":8,fixed:1,cur:"%"},
				{"name":"移动速度","min":2,"max":10,fixed:1,cur:"%"},
			],
			"wakeUpList":[
				{"name":"灵波狂想","item": wakeUpItem},{"name":"炙热焰星","item": wakeUpItem},
				{"name":"螺旋烈风","item": wakeUpItem},{"name":"极地冰柱","item": wakeUpItem},
				{"name":"雷电召唤","item": wakeUpItem},{"name":"爆裂突岩","item": wakeUpItem},
				{"name":"地狱火花","item": wakeUpItem},{"name":"龙卷飓风","item": wakeUpItem},
				{"name":"水球凝聚","item": wakeUpItem},{"name":"魔电聚合","item": wakeUpItem},
				{"name":"灼烈幻火","item": wakeUpItem},
				{"name":"风之利刃","item": wakeUpItem},{"name":"激流冲击","item": wakeUpItem},
				{"name":"电闪雷鸣","item": wakeUpItem},{"name":"移山之术","item": wakeUpItem},
				{"name":"浴火凤凰","item": wakeUpItem},{"name":"石枪投射","item": wakeUpItem},
				{"name":"风之真空","item": wakeUpItem},{"name":"雷霆之怒","item": wakeUpItem},
				{"name":"冰枪投射","item": wakeUpItem},{"name":"地狱火海","item": wakeUpItem},
				{"name":"地动山摇","item": wakeUpItem},{"name":"狂风怒吼","item": wakeUpItem},
				{"name":"雷阵天惊","item": wakeUpItem},{"name":"毒云密布","item": wakeUpItem},
				{"name":"雪山崩塌","item": wakeUpItem},{"name":"风雷狂袭","item": wakeUpItem},
				{"name":"风沙吞噬","item": wakeUpItem},{"name":"陨石坠落","item": wakeUpItem},
			]
		},
		{
			"name":"卢萨卡的水晶法杖",
			"id":17625,
			"uid":19005,
			"wikiName":"卢萨卡的水晶法杖",
			"minAttack":587,
			"maxAttack":590,
			"job":"魔导士",
			"attackSpeed":"慢",
			"type":"双手武器",
			"imgUrl":"img/卢萨卡的水晶法杖.png",
			"description":"在荒野中发现的制作精良的武器。它充满了力量。国人首把卢萨卡武器由小熊工会团队获得",
			"list":[
				{"name":"全元素精通","min":20,"max":25,fixed:1,cur:"%"},
				{"name":"释法速度","min":28,"max":33,fixed:1,cur:"%"},
				{"name":"智力","min":25,"max":30,cur:""},
				{"name":"减速概率","min":4,"max":9,fixed:1,cur:"%"},
			],
			"uList":[
				{"name":"攻击力","min":3,"max":8,fixed:1,cur:"%"},
				{"name":"生命偷取","min":6,"max":15,fixed:10,cur:"%"},
				{"name":"增加HP","min":3,"max":8,fixed:1,cur:"%"},
				{"name":"体质","min":2,"max":10,fixed:1,cur:""},
				{"name":"智力","min":2,"max":10,fixed:1,cur:""},
				{"name":"格挡","min":3,"max":8,fixed:1,cur:"%"},
				{"name":"pve伤害","min":3,"max":8,fixed:1,cur:"%"},
				{"name":"pvp伤害","min":3,"max":8,fixed:1,cur:"%"},
				{"name":"释法速度","min":3,"max":10,fixed:1,cur:"%"},
				{"name":"全元素精通","min":3,"max":8,fixed:1,cur:"%"},
				{"name":"移动速度","min":2,"max":10,fixed:1,cur:"%"},
			],
			"wakeUpList":[
				{"name":"灵波狂想","item": wakeUpItem},{"name":"炙热焰星","item": wakeUpItem},
				{"name":"螺旋烈风","item": wakeUpItem},{"name":"极地冰柱","item": wakeUpItem},
				{"name":"雷电召唤","item": wakeUpItem},{"name":"爆裂突岩","item": wakeUpItem},
				{"name":"地狱火花","item": wakeUpItem},{"name":"龙卷飓风","item": wakeUpItem},
				{"name":"水球凝聚","item": wakeUpItem},{"name":"魔电聚合","item": wakeUpItem},
				{"name":"灼烈幻火","item": wakeUpItem},
				{"name":"风之利刃","item": wakeUpItem},{"name":"激流冲击","item": wakeUpItem},
				{"name":"电闪雷鸣","item": wakeUpItem},{"name":"移山之术","item": wakeUpItem},
				{"name":"浴火凤凰","item": wakeUpItem},{"name":"石枪投射","item": wakeUpItem},
				{"name":"风之真空","item": wakeUpItem},{"name":"雷霆之怒","item": wakeUpItem},
				{"name":"冰枪投射","item": wakeUpItem},{"name":"地狱火海","item": wakeUpItem},
				{"name":"地动山摇","item": wakeUpItem},{"name":"狂风怒吼","item": wakeUpItem},
				{"name":"雷阵天惊","item": wakeUpItem},{"name":"毒云密布","item": wakeUpItem},
				{"name":"雪山崩塌","item": wakeUpItem},{"name":"风雷狂袭","item": wakeUpItem},
				{"name":"风沙吞噬","item": wakeUpItem},{"name":"陨石坠落","item": wakeUpItem},
			]
		},
		{
			"name":"卢萨卡法杖",
			"id":9319,
			"uid":19489,
			"wikiName":"卢萨卡法杖",
			"minAttack":587,
			"maxAttack":590,
			"job":"魔导士",
			"attackSpeed":"慢",
			"type":"双手武器",
			"imgUrl":"img/卢萨卡法杖.png",
			"description":"在荒野中发现的制作精良的武器。它充满了力量。国人首把卢萨卡武器由小熊工会团队获得",
			"list":[
				{"name":"最大HP","min":25,"max":30,fixed:1,cur:"%"},
				{"name":"体质","min":25,"max":30,fixed:1,cur:""},
				{"name":"承受伤害","min":6,"max":10,fixed:1,cur:"%"},
				{"name":"减速概率","min":4,"max":9,fixed:1,cur:"%"},
			],
			"uList":[
				{"name":"攻击力","min":3,"max":8,fixed:1,cur:"%"},
				{"name":"生命偷取","min":6,"max":15,fixed:10,cur:"%"},
				{"name":"增加HP","min":3,"max":8,fixed:1,cur:"%"},
				{"name":"体质","min":2,"max":10,fixed:1,cur:""},
				{"name":"智力","min":2,"max":10,fixed:1,cur:""},
				{"name":"格挡","min":3,"max":8,fixed:1,cur:"%"},
				{"name":"pve伤害","min":3,"max":8,fixed:1,cur:"%"},
				{"name":"pvp伤害","min":3,"max":8,fixed:1,cur:"%"},
				{"name":"释法速度","min":3,"max":10,fixed:1,cur:"%"},
				{"name":"全元素精通","min":3,"max":8,fixed:1,cur:"%"},
				{"name":"移动速度","min":2,"max":10,fixed:1,cur:"%"},
			],
			"wakeUpList":[
				{"name":"灵波狂想","item": wakeUpItem},{"name":"炙热焰星","item": wakeUpItem},
				{"name":"螺旋烈风","item": wakeUpItem},{"name":"极地冰柱","item": wakeUpItem},
				{"name":"雷电召唤","item": wakeUpItem},{"name":"爆裂突岩","item": wakeUpItem},
				{"name":"地狱火花","item": wakeUpItem},{"name":"龙卷飓风","item": wakeUpItem},
				{"name":"水球凝聚","item": wakeUpItem},{"name":"魔电聚合","item": wakeUpItem},
				{"name":"灼烈幻火","item": wakeUpItem},
				{"name":"风之利刃","item": wakeUpItem},{"name":"激流冲击","item": wakeUpItem},
				{"name":"电闪雷鸣","item": wakeUpItem},{"name":"移山之术","item": wakeUpItem},
				{"name":"浴火凤凰","item": wakeUpItem},{"name":"石枪投射","item": wakeUpItem},
				{"name":"风之真空","item": wakeUpItem},{"name":"雷霆之怒","item": wakeUpItem},
				{"name":"冰枪投射","item": wakeUpItem},{"name":"地狱火海","item": wakeUpItem},
				{"name":"地动山摇","item": wakeUpItem},{"name":"狂风怒吼","item": wakeUpItem},
				{"name":"雷阵天惊","item": wakeUpItem},{"name":"毒云密布","item": wakeUpItem},
				{"name":"雪山崩塌","item": wakeUpItem},{"name":"风雷狂袭","item": wakeUpItem},
				{"name":"风沙吞噬","item": wakeUpItem},{"name":"陨石坠落","item": wakeUpItem},
			]
		},
		{
			"name":"呼风唤雨",
			"id":13845,
			"uid":14085,
			"wikiName":"呼风唤雨",
			"minAttack":575,
			"maxAttack":577,
			"job":"魔导士",
			"attackSpeed":"非常慢",
			"type":"单手武器",
			"imgUrl":"img/潮汐魔杖.png",
			"description":"在荒野中发现的制作精良的武器。它充满了力量。国人首把卢萨卡武器由小熊工会团队获得",
			"list":[
				{"name":"攻击力","min":15,"max":20,fixed:1,cur:"%"},
				{"name":"释法速度","min":23,"max":28,fixed:1,cur:"%"},
				{"name":"智力","min":23,"max":28,cur:""},
				{"name":"水炸弹概率","min":4,"max":9,fixed:1,cur:"%"},
			],
			"uList":[
				{"name":"攻击力","min":3,"max":8,fixed:1,cur:"%"},
				{"name":"生命偷取","min":6,"max":15,fixed:10,cur:"%"},
				{"name":"增加HP","min":3,"max":8,fixed:1,cur:"%"},
				{"name":"体质","min":2,"max":10,fixed:1,cur:""},
				{"name":"智力","min":2,"max":10,fixed:1,cur:""},
				{"name":"格挡","min":3,"max":8,fixed:1,cur:"%"},
				{"name":"pve伤害","min":3,"max":8,fixed:1,cur:"%"},
				{"name":"pvp伤害","min":3,"max":8,fixed:1,cur:"%"},
				{"name":"释法速度","min":3,"max":10,fixed:1,cur:"%"},
				{"name":"反射伤害","min":10,"max":20,fixed:1,cur:"%"},
				{"name":"移动速度","min":2,"max":10,fixed:1,cur:"%"},
			],
			"wakeUpList":[
				{"name":"灵波狂想","item": wakeUpItem},{"name":"炙热焰星","item": wakeUpItem},
				{"name":"螺旋烈风","item": wakeUpItem},{"name":"极地冰柱","item": wakeUpItem},
				{"name":"雷电召唤","item": wakeUpItem},{"name":"爆裂突岩","item": wakeUpItem},
				{"name":"地狱火花","item": wakeUpItem},{"name":"龙卷飓风","item": wakeUpItem},
				{"name":"水球凝聚","item": wakeUpItem},{"name":"魔电聚合","item": wakeUpItem},
				{"name":"灼烈幻火","item": wakeUpItem},
				{"name":"风之利刃","item": wakeUpItem},{"name":"激流冲击","item": wakeUpItem},
				{"name":"电闪雷鸣","item": wakeUpItem},{"name":"移山之术","item": wakeUpItem},
				{"name":"灵念弹","item": wakeUpItem},{"name":"万念俱灰","item": wakeUpItem},
				{"name":"混沌封印","item": wakeUpItem},{"name":"神力攻击","item": wakeUpItem},
				{"name":"幻象恐惧","item": wakeUpItem},{"name":"灵力墙","item": wakeUpItem}
			]
		},
		{
			"name":"卢萨卡的水晶魔杖",
			"id":15903,
			"uid":19761,
			"wikiName":"卢萨卡的水晶魔杖",
			"minAttack":595,
			"maxAttack":597,
			"job":"魔导士",
			"attackSpeed":"非常慢",
			"type":"单手武器",
			"imgUrl":"img/卢萨卡的水晶魔杖.png",
			"description":"在荒野中发现的制作精良的武器。它充满了力量。国人首把卢萨卡武器由小熊工会团队获得",
			"list":[
				{"name":"攻击力","min":17,"max":22,fixed:1,cur:"%"},
				{"name":"释法速度","min":25,"max":30,fixed:1,cur:"%"},
				{"name":"智力","min":25,"max":30,cur:""},
				{"name":"减速概率","min":4,"max":9,fixed:1,cur:"%"},
			],
			"uList":[
				{"name":"攻击力","min":3,"max":8,fixed:1,cur:"%"},
				{"name":"生命偷取","min":6,"max":15,fixed:10,cur:"%"},
				{"name":"增加HP","min":3,"max":8,fixed:1,cur:"%"},
				{"name":"体质","min":2,"max":10,fixed:1,cur:""},
				{"name":"智力","min":2,"max":10,fixed:1,cur:""},
				{"name":"格挡","min":3,"max":8,fixed:1,cur:"%"},
				{"name":"pve伤害","min":3,"max":8,fixed:1,cur:"%"},
				{"name":"pvp伤害","min":3,"max":8,fixed:1,cur:"%"},
				{"name":"释法速度","min":3,"max":10,fixed:1,cur:"%"},
				{"name":"反射伤害","min":10,"max":20,fixed:1,cur:"%"},
				{"name":"移动速度","min":2,"max":10,fixed:1,cur:"%"},
			],
			"wakeUpList":[
				{"name":"灵波狂想","item": wakeUpItem},{"name":"炙热焰星","item": wakeUpItem},
				{"name":"螺旋烈风","item": wakeUpItem},{"name":"极地冰柱","item": wakeUpItem},
				{"name":"雷电召唤","item": wakeUpItem},{"name":"爆裂突岩","item": wakeUpItem},
				{"name":"地狱火花","item": wakeUpItem},{"name":"龙卷飓风","item": wakeUpItem},
				{"name":"水球凝聚","item": wakeUpItem},{"name":"魔电聚合","item": wakeUpItem},
				{"name":"灼烈幻火","item": wakeUpItem},
				{"name":"风之利刃","item": wakeUpItem},{"name":"激流冲击","item": wakeUpItem},
				{"name":"电闪雷鸣","item": wakeUpItem},{"name":"移山之术","item": wakeUpItem},
				{"name":"灵念弹","item": wakeUpItem},{"name":"万念俱灰","item": wakeUpItem},
				{"name":"混沌封印","item": wakeUpItem},{"name":"神力攻击","item": wakeUpItem},
				{"name":"幻象恐惧","item": wakeUpItem},{"name":"灵力墙","item": wakeUpItem}
			]
		},
		{
			"name":"卢萨卡魔杖",
			"id":12508,
			"uid":15677,
			"wikiName":"卢萨卡魔杖",
			"minAttack":595,
			"maxAttack":597,
			"job":"魔导士",
			"attackSpeed":"非常慢",
			"type":"单手武器",
			"imgUrl":"img/卢萨卡魔杖.png",
			"description":"在荒野中发现的制作精良的武器。它充满了力量。国人首把卢萨卡武器由小熊工会团队获得",
			"list":[
				{"name":"最大HP","min":25,"max":30,fixed:1,cur:"%"},
				{"name":"体质","min":25,"max":30,fixed:1,cur:""},
				{"name":"承受伤害","min":6,"max":10,fixed:1,cur:"%"},
				{"name":"减速概率","min":4,"max":9,fixed:1,cur:"%"},
			],
			"uList":[
				{"name":"攻击力","min":3,"max":8,fixed:1,cur:"%"},
				{"name":"生命偷取","min":6,"max":15,fixed:10,cur:"%"},
				{"name":"增加HP","min":3,"max":8,fixed:1,cur:"%"},
				{"name":"体质","min":2,"max":10,fixed:1,cur:""},
				{"name":"智力","min":2,"max":10,fixed:1,cur:""},
				{"name":"格挡","min":3,"max":8,fixed:1,cur:"%"},
				{"name":"pve伤害","min":3,"max":8,fixed:1,cur:"%"},
				{"name":"pvp伤害","min":3,"max":8,fixed:1,cur:"%"},
				{"name":"释法速度","min":3,"max":10,fixed:1,cur:"%"},
				{"name":"反射伤害","min":10,"max":20,fixed:1,cur:"%"},
				{"name":"移动速度","min":2,"max":10,fixed:1,cur:"%"},
			],
			"wakeUpList":[
				{"name":"灵波狂想","item": wakeUpItem},{"name":"炙热焰星","item": wakeUpItem},
				{"name":"螺旋烈风","item": wakeUpItem},{"name":"极地冰柱","item": wakeUpItem},
				{"name":"雷电召唤","item": wakeUpItem},{"name":"爆裂突岩","item": wakeUpItem},
				{"name":"地狱火花","item": wakeUpItem},{"name":"龙卷飓风","item": wakeUpItem},
				{"name":"水球凝聚","item": wakeUpItem},{"name":"魔电聚合","item": wakeUpItem},
				{"name":"灼烈幻火","item": wakeUpItem},
				{"name":"风之利刃","item": wakeUpItem},{"name":"激流冲击","item": wakeUpItem},
				{"name":"电闪雷鸣","item": wakeUpItem},{"name":"移山之术","item": wakeUpItem},
				{"name":"灵念弹","item": wakeUpItem},{"name":"万念俱灰","item": wakeUpItem},
				{"name":"混沌封印","item": wakeUpItem},{"name":"神力攻击","item": wakeUpItem},
				{"name":"幻象恐惧","item": wakeUpItem},{"name":"灵力墙","item": wakeUpItem}
			]
		},
		{
			"name":"塞壬之歌",
			"id":16918,
			"uid":11124,
			"wikiName":"塞壬之歌",
			"minAttack":527,
			"maxAttack":529,
			"job":"圣职者",
			"attackSpeed":"通用",
			"type":"双手武器",
			"imgUrl":"img/潮汐魔棒.png",
			"description":"在荒野中发现的制作精良的武器。它充满了力量。国人首把卢萨卡武器由小熊工会团队获得",
			"list":[
				{"name":"攻击力","min":10,"max":15,fixed:1,cur:"%"},
				{"name":"治疗","min":10,"max":15,fixed:1,cur:"%"},
				{"name":"释法速度","min":26,"max":30,fixed:1,cur:"%"},
				{"name":"水炸弹概率","min":4,"max":9,fixed:1,cur:"%"},
			],
			"uList":[
				{"name":"攻击力","min":3,"max":8,fixed:1,cur:"%"},
				{"name":"生命偷取","min":6,"max":15,fixed:10,cur:"%"},
				{"name":"增加HP","min":3,"max":8,fixed:1,cur:"%"},
				{"name":"体质","min":2,"max":10,fixed:1,cur:""},
				{"name":"智力","min":2,"max":10,fixed:1,cur:""},
				{"name":"格挡","min":3,"max":8,fixed:1,cur:"%"},
				{"name":"pve伤害","min":3,"max":8,fixed:1,cur:"%"},
				{"name":"pvp伤害","min":3,"max":8,fixed:1,cur:"%"},
				{"name":"释法速度","min":3,"max":10,fixed:1,cur:"%"},
				{"name":"治疗","min":3,"max":10,fixed:1,cur:"%"},
			],
			"wakeUpList":[
				{"name":"治疗","item": ["5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25"]},
				{"name":"月光惩戒","item": wakeUpItem},{"name":"神圣领域","item": wakeUpItem},
			]
		},
		{
			"name":"卢萨卡的水晶魔棒",
			"id":18022,
			"uid":18617,
			"wikiName":"卢萨卡的水晶魔棒",
			"minAttack":547,
			"maxAttack":549,
			"job":"圣职者",
			"attackSpeed":"通用",
			"type":"双手武器",
			"imgUrl":"img/卢萨卡的水晶魔棒.png",
			"description":"在荒野中发现的制作精良的武器。它充满了力量。国人首把卢萨卡武器由小熊工会团队获得",
			"list":[
				{"name":"攻击力","min":12,"max":17,fixed:1,cur:"%"},
				{"name":"治疗","min":12,"max":17,fixed:1,cur:"%"},
				{"name":"释法速度","min":28,"max":33,fixed:1,cur:"%"},
				{"name":"智力","min":25,"max":30,fixed:1,cur:""},
			],
			"uList":[
				{"name":"攻击力","min":3,"max":8,fixed:1,cur:"%"},
				{"name":"生命偷取","min":6,"max":15,fixed:10,cur:"%"},
				{"name":"增加HP","min":3,"max":8,fixed:1,cur:"%"},
				{"name":"体质","min":2,"max":10,fixed:1,cur:""},
				{"name":"智力","min":2,"max":10,fixed:1,cur:""},
				{"name":"格挡","min":3,"max":8,fixed:1,cur:"%"},
				{"name":"pve伤害","min":3,"max":8,fixed:1,cur:"%"},
				{"name":"pvp伤害","min":3,"max":8,fixed:1,cur:"%"},
				{"name":"释法速度","min":3,"max":10,fixed:1,cur:"%"},
				{"name":"治疗","min":3,"max":10,fixed:1,cur:"%"},
			],
			"wakeUpList":[
				{"name":"治疗","item": ["5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25"]},
				{"name":"月光惩戒","item": wakeUpItem},{"name":"神圣领域","item": wakeUpItem},
			]
		},
		{
			"name":"卢萨卡魔棒",
			"id":15880,
			"uid":18949,
			"wikiName":"卢萨卡魔棒",
			"minAttack":547,
			"maxAttack":549,
			"job":"圣职者",
			"attackSpeed":"通用",
			"type":"双手武器",
			"imgUrl":"img/卢萨卡魔棒.png",
			"description":"在荒野中发现的制作精良的武器。它充满了力量。国人首把卢萨卡武器由小熊工会团队获得",
			"list":[
				{"name":"最大HP","min":25,"max":30,fixed:1,cur:"%"},
				{"name":"体质","min":25,"max":30,fixed:1,cur:""},
				{"name":"承受伤害","min":6,"max":10,fixed:1,cur:"%"},
				{"name":"击晕概率(PVE)","min":1,"max":3,fixed:1,cur:"%"},
				{"name":"击晕概率(PVP)","min":1,"max":3,fixed:1,cur:"%"},
			],
			"uList":[
				{"name":"攻击力","min":3,"max":8,fixed:1,cur:"%"},
				{"name":"生命偷取","min":6,"max":15,fixed:10,cur:"%"},
				{"name":"增加HP","min":3,"max":8,fixed:1,cur:"%"},
				{"name":"体质","min":2,"max":10,fixed:1,cur:""},
				{"name":"智力","min":2,"max":10,fixed:1,cur:""},
				{"name":"格挡","min":3,"max":8,fixed:1,cur:"%"},
				{"name":"pve伤害","min":3,"max":8,fixed:1,cur:"%"},
				{"name":"pvp伤害","min":3,"max":8,fixed:1,cur:"%"},
				{"name":"释法速度","min":3,"max":10,fixed:1,cur:"%"},
				{"name":"治疗","min":3,"max":10,fixed:1,cur:"%"},
			],
			"wakeUpList":[
				{"name":"治疗","item": ["5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25"]},
				{"name":"月光惩戒","item": wakeUpItem},{"name":"神圣领域","item": wakeUpItem},
			]
		},
		{
			"name":"潮汐之拳",
			"id":14971,
			"uid":16906,
			"wikiName":"潮汐之拳",
			"minAttack":543,
			"maxAttack":545,
			"job":"圣职者",
			"attackSpeed":"快速",
			"type":"单手武器",
			"imgUrl":"img/潮汐拳套.png",
			"description":"在荒野中发现的制作精良的武器。它充满了力量。国人首把卢萨卡武器由小熊工会团队获得",
			"list":[
				{"name":"暴击伤害","min":480,"max":580,fixed:10,cur:"%"},
				{"name":"暴击","min":280,"max":340,fixed:10,cur:"%"},
				{"name":"攻击速度","min":90,"max":115,fixed:10,cur:"%"},
				{"name":"水炸弹概率","min":4,"max":9,fixed:1,cur:"%"},
			],
			"uList":[
				{"name":"暴击伤害","min":30,"max":100,fixed:10,cur:"%"},
				{"name":"格挡穿透","min":30,"max":100,fixed:10,cur:"%"},
				{"name":"暴击率","min":30,"max":100,fixed:10,cur:"%"},
				{"name":"攻击力","min":3,"max":8,fixed:1,cur:"%"},
				{"name":"生命偷取","min":6,"max":15,fixed:10,cur:"%"},
				{"name":"增加HP","min":3,"max":8,fixed:1,cur:"%"},
				{"name":"力量","min":2,"max":10,fixed:1,cur:""},
				{"name":"体质","min":2,"max":10,fixed:1,cur:""},
				{"name":"敏捷","min":2,"max":10,fixed:1,cur:""},
				{"name":"智力","min":2,"max":10,fixed:1,cur:""},
				{"name":"格挡","min":3,"max":8,fixed:1,cur:"%"},
				{"name":"pve伤害","min":3,"max":8,fixed:1,cur:"%"},
				{"name":"pvp伤害","min":3,"max":8,fixed:1,cur:"%"},
			],
			"wakeUpList":[
				{"name":"圣光破","item": wakeUpItem},{"name":"神光破","item": wakeUpItem},
				{"name":"圣光大地","item": wakeUpItem},
				{"name":"背水一击","item": ["2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12"]},
				{"name":"血舞","item": wakeUpItem},{"name":"星之咒","item": wakeUpItem},
				{"name":"斗气风暴","item": wakeUpItem},{"name":"拳之聚","item": wakeUpItem},
				{"name":"流星拳","item": wakeUpItem},{"name":"冲击拳","item": wakeUpItem},
			]
		},
		{
			"name":"卢萨卡的水晶拳",
			"id":14100,
			"uid":15019,
			"wikiName":"卢萨卡的水晶拳",
			"minAttack":563,
			"maxAttack":565,
			"job":"圣职者",
			"attackSpeed":"快速",
			"type":"单手武器",
			"imgUrl":"img/卢萨卡的水晶拳.png",
			"description":"在荒野中发现的制作精良的武器。它充满了力量。国人首把卢萨卡武器由小熊工会团队获得。",
			"list":[
				{"name":"暴击伤害","min":550,"max":650,fixed:10,cur:"%"},
				{"name":"暴击","min":290,"max":350,fixed:10,cur:"%"},
				{"name":"攻击速度","min":100,"max":125,fixed:10,cur:"%"},
				{"name":"击晕概率(PVE)","min":1,"max":3,fixed:1,cur:"%"},
				{"name":"击晕概率(PVP)","min":1,"max":3,fixed:1,cur:"%"},
			],
			"uList":[
				{"name":"暴击伤害","min":30,"max":100,fixed:10,cur:"%"},
				{"name":"格挡穿透","min":30,"max":100,fixed:10,cur:"%"},
				{"name":"暴击率","min":30,"max":100,fixed:10,cur:"%"},
				{"name":"攻击力","min":3,"max":8,fixed:1,cur:"%"},
				{"name":"生命偷取","min":6,"max":15,fixed:10,cur:"%"},
				{"name":"增加HP","min":3,"max":8,fixed:1,cur:"%"},
				{"name":"力量","min":2,"max":10,fixed:1,cur:""},
				{"name":"体质","min":2,"max":10,fixed:1,cur:""},
				{"name":"敏捷","min":2,"max":10,fixed:1,cur:""},
				{"name":"智力","min":2,"max":10,fixed:1,cur:""},
				{"name":"格挡","min":3,"max":8,fixed:1,cur:"%"},
				{"name":"pve伤害","min":3,"max":8,fixed:1,cur:"%"},
				{"name":"pvp伤害","min":3,"max":8,fixed:1,cur:"%"},
			],
			"wakeUpList":[
				{"name":"圣光破","item": wakeUpItem},{"name":"神光破","item": wakeUpItem},
				{"name":"圣光大地","item": wakeUpItem},
				{"name":"背水一击","item": ["2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12"]},
				{"name":"血舞","item": wakeUpItem},{"name":"星之咒","item": wakeUpItem},
				{"name":"斗气风暴","item": wakeUpItem},{"name":"拳之聚","item": wakeUpItem},
				{"name":"流星拳","item": wakeUpItem},{"name":"冲击拳","item": wakeUpItem},
			]
		},
		{
			"name":"卢萨卡之拳",
			"id":12648,
			"uid":16135,
			"wikiName":"卢萨卡之拳",
			"minAttack":563,
			"maxAttack":565,
			"job":"圣职者",
			"attackSpeed":"快速",
			"type":"单手武器",
			"imgUrl":"img/卢萨卡之拳.png",
			"description":"在荒野中发现的制作精良的武器。它充满了力量。国人首把卢萨卡武器由小熊工会团队获得。",
			"list":[
				{"name":"最大HP","min":25,"max":30,fixed:1,cur:"%"},
				{"name":"体质","min":25,"max":30,fixed:1,cur:""},
				{"name":"承受伤害","min":6,"max":10,fixed:1,cur:"%"},
				{"name":"中毒概率","min":4,"max":9,fixed:1,cur:"%"},
			],
			"uList":[
				{"name":"暴击伤害","min":30,"max":100,fixed:10,cur:"%"},
				{"name":"格挡穿透","min":30,"max":100,fixed:10,cur:"%"},
				{"name":"暴击率","min":30,"max":100,fixed:10,cur:"%"},
				{"name":"攻击力","min":3,"max":8,fixed:1,cur:"%"},
				{"name":"生命偷取","min":6,"max":15,fixed:10,cur:"%"},
				{"name":"增加HP","min":3,"max":8,fixed:1,cur:"%"},
				{"name":"力量","min":2,"max":10,fixed:1,cur:""},
				{"name":"体质","min":2,"max":10,fixed:1,cur:""},
				{"name":"敏捷","min":2,"max":10,fixed:1,cur:""},
				{"name":"智力","min":2,"max":10,fixed:1,cur:""},
				{"name":"格挡","min":3,"max":8,fixed:1,cur:"%"},
				{"name":"pve伤害","min":3,"max":8,fixed:1,cur:"%"},
				{"name":"pvp伤害","min":3,"max":8,fixed:1,cur:"%"},
			],
			"wakeUpList":[
				{"name":"圣光破","item": wakeUpItem},{"name":"神光破","item": wakeUpItem},
				{"name":"圣光大地","item": wakeUpItem},
				{"name":"背水一击","item": ["2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12"]},
				{"name":"血舞","item": wakeUpItem},{"name":"星之咒","item": wakeUpItem},
				{"name":"斗气风暴","item": wakeUpItem},{"name":"拳之聚","item": wakeUpItem},
				{"name":"流星拳","item": wakeUpItem},{"name":"冲击拳","item": wakeUpItem},
			]
		}
	];

	//强化数值
	var upList = [
		{"probability":0.888888,"low_probability":0.9,"gold":2000,"yellow":10,"green":10,"four_num":1,"eight_num":0},
		{"probability":0.823529,"low_probability":0.85,"gold":4000,"yellow":14,"green":14,"four_num":1,"eight_num":0},
		{"probability":0.75,"low_probability":0.8,"gold":8000,"yellow":20,"green":20,"four_num":1,"eight_num":0},
		{"probability":0.34737,"low_probability":0.54,"gold":15000,"yellow":27,"green":27,"four_num":1,"eight_num":0},
		{"probability":0.206225,"low_probability":0.405,"gold":30000,"yellow":38,"green":38,"four_num":0,"eight_num":1},
		{"probability":0.097826,"low_probability":0.27,"gold":50000,"yellow":54,"green":54,"four_num":0,"eight_num":1},
		{"probability":0.04562,"low_probability":0.18,"gold":75000,"yellow":75,"green":75,"four_num":0,"eight_num":1},
		{"probability":0.012016,"low_probability":0.09,"gold":125000,"yellow":105,"green":105,"four_num":0,"eight_num":1},
		{"probability":0.003089,"low_probability":0.045,"gold":250000,"yellow":148,"green":148,"four_num":0,"eight_num":1},
		{"probability":0.000502,"low_probability":0.018,"gold":500000,"yellow":207,"green":207,"four_num":0,"eight_num":1},
	];
	
	//单手武器穿洞数值
	var holeList = [
		{"probability":0.888888,"low_probability":0.9,"gold":2000,"yellow":10,"green":10,"four_num":1,"eight_num":0},
		{"probability":0.823529,"low_probability":0.85,"gold":4000,"yellow":14,"green":14,"four_num":1,"eight_num":0},
		{"probability":0.75,"low_probability":0.8,"gold":8000,"yellow":20,"green":20,"four_num":1,"eight_num":0},
		{"probability":0.34737,"low_probability":0.54,"gold":15000,"yellow":27,"green":27,"four_num":1,"eight_num":0},
		{"probability":0.206225,"low_probability":0.405,"gold":30000,"yellow":38,"green":38,"four_num":0,"eight_num":1},
		{"probability":0.097826,"low_probability":0.27,"gold":50000,"yellow":54,"green":54,"four_num":0,"eight_num":1},
		{"probability":0.04562,"low_probability":0.18,"gold":75000,"yellow":75,"green":75,"four_num":0,"eight_num":1},
		{"probability":0.012016,"low_probability":0.09,"gold":125000,"yellow":105,"green":105,"four_num":0,"eight_num":1},
		{"probability":0.003089,"low_probability":0.045,"gold":250000,"yellow":148,"green":148,"four_num":0,"eight_num":1},
		{"probability":0.000502,"low_probability":0.018,"gold":500000,"yellow":207,"green":207,"four_num":0,"eight_num":1},
	];//双手武器穿洞数值
	var doubleholeList = [
		{"probability":0.888888,"low_probability":0.9,"gold":2000,"yellow":10,"green":10,"four_num":1,"eight_num":0},
		{"probability":0.823529,"low_probability":0.85,"gold":4000,"yellow":14,"green":14,"four_num":1,"eight_num":0},
		{"probability":0.75,"low_probability":0.8,"gold":8000,"yellow":20,"green":20,"four_num":1,"eight_num":0},
		{"probability":0.34737,"low_probability":0.54,"gold":15000,"yellow":27,"green":27,"four_num":1,"eight_num":0},
		{"probability":0.206225,"low_probability":0.405,"gold":30000,"yellow":38,"green":38,"four_num":0,"eight_num":1},
		{"probability":0.097826,"low_probability":0.27,"gold":50000,"yellow":54,"green":54,"four_num":0,"eight_num":1},
		{"probability":0.04562,"low_probability":0.18,"gold":75000,"yellow":75,"green":75,"four_num":0,"eight_num":1},
		{"probability":0.012016,"low_probability":0.09,"gold":125000,"yellow":105,"green":105,"four_num":0,"eight_num":1},
		{"probability":0.003089,"low_probability":0.045,"gold":250000,"yellow":148,"green":148,"four_num":0,"eight_num":1},
		{"probability":0.000502,"low_probability":0.018,"gold":500000,"yellow":207,"green":207,"four_num":0,"eight_num":1},
	];
	
	//强化次数,金币,黄矿,绿矿,失败次数,武器强化等级,4点数量,8点数量,武器索引值
	let up_num = 0,gold = 0,yellow = 0,green = 0, failure_num = 0,weapon_lv = 0,four_num = 0,eight_num = 0 ,weapon_index = 0;
	//成功概率
	let probability = 0.000000;
	//成功概率
	let low_probability = 0.000000;
	//唤醒列表
	let wakeUpList = [];
	
	

