let hai_boss_drop = [
	{"id":"19384","name":"Broken Wings","icon":"gengembrokenwings.png","category":"BOOTY","rarity":"common","probability":0.99,"num":0},
	{"id":"4503","name":"海鲜披萨","icon":"genfoocoopizza.png","category":"RECOVERY","rarity":"common","probability":0.60,"num":0},
	{"id":"6234","name":"终极魔力多","icon":"genpotrefr10.png","category":"RECOVERY","rarity":"common","probability":0.60,"num":0},
	{"id":"3880","name":"活力饮料900","icon":"genpotdrivithig3.png","category":"RECOVERY","rarity":"common","probability":0.60,"num":0},
	{"id":"11682","name":"珊瑚岛咖喱","icon":"genfoocoocoralcurry.png","category":"RECOVERY","rarity":"common","probability":0.20,"num":0},
	{"id":"15625","name":"终极精粹","icon":"ultimaquest.png","category":"MATERIAL","rarity":"common","probability":0.05,"num":0},
	{"id":"814","name":"PK纸片","icon":"chppk.png","category":"SCROLL","rarity":"rare","probability":0.05,"num":0},
	{"id":"15403","name":"晶石","icon":"genmatorichalcum01.png","category":"MATERIAL","rarity":"veryrare","probability":0.02,"num":0},
	{"id":"7867","name":"8点精炼骰子","icon":"genmatdieeight.png","category":"MATERIAL","rarity":"uncommon","probability":0.01,"num":0},
	{"id":"4095","name":"Aquanar Helmet","icon":"mbil04cap-et01.png","category":"ARMOR","rarity":"common","probability":0.01,"num":0},
	{"id":"12332","name":"Aquanar Gauntlets","icon":"mbil04hand-et01.png","category":"ARMOR","rarity":"common","probability":0.01,"num":0},
	{"id":"15862","name":"Aquanar Boots","icon":"mbil04foot-et01.png","category":"ARMOR","rarity":"common","probability":0.01,"num":0},
	{"id":"16124","name":"Aqualis Helmet","icon":"fbil04cap-et01.png","category":"ARMOR","rarity":"common","probability":0.01,"num":0},
	{"id":"11650","name":"Aqualis Gauntlets","icon":"fbil04hand-et01.png","category":"ARMOR","rarity":"common","probability":0.01,"num":0},
	{"id":"18535","name":"Aqualis Boots","icon":"fbil04foot-et01.png","category":"ARMOR","rarity":"common","probability":0.01,"num":0},
	{"id":"10967","name":"Seakissed Aquanar Helmet","icon":"mbil04cap-et01.png","category":"ARMOR","rarity":"uncommon","probability":0.01,"num":0},
	{"id":"17563","name":"Seakissed Aquanar Gauntlets","icon":"mbil04hand-et01.png","category":"ARMOR","rarity":"uncommon","probability":0.01,"num":0},
	{"id":"18147","name":"Seakissed Aquanar Boots","icon":"mbil04foot-et01.png","category":"ARMOR","rarity":"uncommon","probability":0.01,"num":0},
	{"id":"19079","name":"Seakissed Aqualis Helmet","icon":"fbil04cap-et01.png","category":"ARMOR","rarity":"uncommon","probability":0.01,"num":0},
	{"id":"18008","name":"Seakissed Aqualis Gauntlets","icon":"fbil04hand-et01.png","category":"ARMOR","rarity":"uncommon","probability":0.01,"num":0},
	{"id":"16467","name":"Seakissed Aqualis Boots","icon":"fbil04foot-et01.png","category":"ARMOR","rarity":"uncommon","probability":0.01,"num":0},
	{"id":"10725","name":"Marinthor Helmet","icon":"mbla04cap-et01.png","category":"ARMOR","rarity":"common","probability":0.01,"num":0},
	{"id":"19923","name":"Marinthor Gauntlets","icon":"mbla04hand-et01.png","category":"ARMOR","rarity":"common","probability":0.01,"num":0},
	{"id":"14283","name":"Marinthor Boots","icon":"mbla04foot-et01.png","category":"ARMOR","rarity":"common","probability":0.01,"num":0},
	{"id":"16660","name":"Marinva Helmet","icon":"fbla04cap-et01.png","category":"ARMOR","rarity":"common","probability":0.01,"num":0},
	{"id":"18685","name":"Marinva Gauntlets","icon":"fbla04hand-et01.png","category":"ARMOR","rarity":"common","probability":0.01,"num":0},
	{"id":"16640","name":"Marinva Boots","icon":"fbla04foot-et01.png","category":"ARMOR","rarity":"common","probability":0.01,"num":0},
	{"id":"17832","name":"Seakissed Marinthor Helmet","icon":"mbla04cap-et01.png","category":"ARMOR","rarity":"uncommon","probability":0.01,"num":0},
	{"id":"10275","name":"Seakissed Marinthor Gauntlets","icon":"mbla04hand-et01.png","category":"ARMOR","rarity":"uncommon","probability":0.01,"num":0},
	{"id":"17503","name":"Seakissed Marinthor Boots","icon":"mbla04foot-et01.png","category":"ARMOR","rarity":"uncommon","probability":0.01,"num":0},
	{"id":"18098","name":"Seakissed Marinva Helmet","icon":"fbla04cap-et01.png","category":"ARMOR","rarity":"uncommon","probability":0.01,"num":0},
	{"id":"12965","name":"Seakissed Marinva Gauntlets","icon":"fbla04hand-et01.png","category":"ARMOR","rarity":"uncommon","probability":0.01,"num":0},
	{"id":"12727","name":"Seakissed Marinva Boots","icon":"fbla04foot-et01.png","category":"ARMOR","rarity":"uncommon","probability":0.01,"num":0},
	{"id":"17894","name":"Sealith Helmet","icon":"mele04cap-et01.png","category":"ARMOR","rarity":"common","probability":0.01,"num":0},
	{"id":"12806","name":"Sealith Gauntlets","icon":"mele04hand-et01.png","category":"ARMOR","rarity":"common","probability":0.01,"num":0},
	{"id":"14625","name":"Sealith Boots","icon":"mele04foot-et01.png","category":"ARMOR","rarity":"common","probability":0.01,"num":0},
	{"id":"15564","name":"Seavara Helmet","icon":"fele04cap-et01.png","category":"ARMOR","rarity":"common","probability":0.01,"num":0},
	{"id":"13773","name":"Seavara Gauntlets","icon":"fele04hand-et01.png","category":"ARMOR","rarity":"common","probability":0.01,"num":0},
	{"id":"10323","name":"Seavara Boots","icon":"fele04foot-et01.png","category":"ARMOR","rarity":"common","probability":0.01,"num":0},
	{"id":"12689","name":"Seakissed Sealith Helmet","icon":"mele04cap-et01.png","category":"ARMOR","rarity":"uncommon","probability":0.01,"num":0},
	{"id":"19321","name":"Seakissed Sealith Gauntlets","icon":"mele04hand-et01.png","category":"ARMOR","rarity":"uncommon","probability":0.01,"num":0},
	{"id":"12922","name":"Seakissed Sealith Boots","icon":"mele04foot-et01.png","category":"ARMOR","rarity":"uncommon","probability":0.01,"num":0},
	{"id":"14118","name":"Seakissed Seavara Helmet","icon":"fele04cap-et01.png","category":"ARMOR","rarity":"uncommon","probability":0.01,"num":0},
	{"id":"15423","name":"Seakissed Seavara Gauntlets","icon":"fele04hand-et01.png","category":"ARMOR","rarity":"uncommon","probability":0.01,"num":0},
	{"id":"11628","name":"Seakissed Seavara Boots","icon":"fele04foot-et01.png","category":"ARMOR","rarity":"uncommon","probability":0.01,"num":0},
	{"id":"13664","name":"Brinex Helmet","icon":"mjst04cap-et01.png","category":"ARMOR","rarity":"common","probability":0.01,"num":0},
	{"id":"10840","name":"Brinex Gauntlets","icon":"mjst04hand-et01.png","category":"ARMOR","rarity":"common","probability":0.01,"num":0},
	{"id":"13248","name":"Brinex Boots","icon":"mjst04foot-et01.png","category":"ARMOR","rarity":"common","probability":0.01,"num":0},
	{"id":"14423","name":"Brineya Helmet","icon":"fjst04cap-et01.png","category":"ARMOR","rarity":"common","probability":0.01,"num":0},
	{"id":"12587","name":"Brineya Gauntlets","icon":"fjst04hand-et01.png","category":"ARMOR","rarity":"common","probability":0.01,"num":0},
	{"id":"16643","name":"Brineya Boots","icon":"fjst04foot-et01.png","category":"ARMOR","rarity":"common","probability":0.01,"num":0},
	{"id":"14169","name":"Seakissed Brinex Helmet","icon":"mjst04cap-et01.png","category":"ARMOR","rarity":"uncommon","probability":0.01,"num":0},
	{"id":"10814","name":"Seakissed Brinex Gauntlets","icon":"mjst04hand-et01.png","category":"ARMOR","rarity":"uncommon","probability":0.01,"num":0},
	{"id":"12195","name":"Seakissed Brinex Boots","icon":"mjst04foot-et01.png","category":"ARMOR","rarity":"uncommon","probability":0.01,"num":0},
	{"id":"14561","name":"Seakissed Brineya Helmet","icon":"fjst04cap-et01.png","category":"ARMOR","rarity":"uncommon","probability":0.01,"num":0},
	{"id":"11773","name":"Seakissed Brineya Gauntlets","icon":"fjst04hand-et01.png","category":"ARMOR","rarity":"uncommon","probability":0.01,"num":0},
	{"id":"13394","name":"Seakissed Brineya Boots","icon":"fjst04foot-et01.png","category":"ARMOR","rarity":"uncommon","probability":0.01,"num":0},
	{"id":"10559","name":"Tidewhis Helmet","icon":"mkin04cap-et01.png","category":"ARMOR","rarity":"common","probability":0.01,"num":0},
	{"id":"14318","name":"Tidewhis Gauntlets","icon":"mkin04hand-et01.png","category":"ARMOR","rarity":"common","probability":0.01,"num":0},
	{"id":"17087","name":"Tidewhis Boots","icon":"mkin04foot-et01.png","category":"ARMOR","rarity":"common","probability":0.01,"num":0},
	{"id":"11295","name":"Tidera Helmet","icon":"fkin04cap-et01.png","category":"ARMOR","rarity":"common","probability":0.01,"num":0},
	{"id":"18078","name":"Tidera Gauntlets","icon":"fkin04hand-et01.png","category":"ARMOR","rarity":"common","probability":0.01,"num":0},
	{"id":"14617","name":"Tidera Boots","icon":"fkin04foot-et01.png","category":"ARMOR","rarity":"common","probability":0.01,"num":0},
	{"id":"11697","name":"Seakissed Tidewhis Helmet","icon":"mkin04cap-et01.png","category":"ARMOR","rarity":"uncommon","probability":0.01,"num":0},
	{"id":"15319","name":"Seakissed Tidewhis Gauntlets","icon":"mkin04hand-et01.png","category":"ARMOR","rarity":"uncommon","probability":0.01,"num":0},
	{"id":"11751","name":"Seakissed Tidewhis Boots","icon":"mkin04foot-et01.png","category":"ARMOR","rarity":"uncommon","probability":0.01,"num":0},
	{"id":"11195","name":"Seakissed Tidera Helmet","icon":"fkin04cap-et01.png","category":"ARMOR","rarity":"uncommon","probability":0.01,"num":0},
	{"id":"17121","name":"Seakissed Tidera Gauntlets","icon":"fkin04hand-et01.png","category":"ARMOR","rarity":"uncommon","probability":0.01,"num":0},
	{"id":"11114","name":"Seakissed Tidera Boots","icon":"fkin04foot-et01.png","category":"ARMOR","rarity":"uncommon","probability":0.01,"num":0},
	{"id":"16353","name":"Aquiloop Helmet","icon":"mpsy04cap-et01.png","category":"ARMOR","rarity":"common","probability":0.01,"num":0},
	{"id":"10845","name":"Aquiloop Gauntlets","icon":"mpsy04hand-et01.png","category":"ARMOR","rarity":"common","probability":0.01,"num":0},
	{"id":"12367","name":"Aquiloop Boots","icon":"mpsy04foot-et01.png","category":"ARMOR","rarity":"common","probability":0.01,"num":0},
	{"id":"15808","name":"Aquiva Helmet","icon":"fpsy04cap-et01.png","category":"ARMOR","rarity":"common","probability":0.01,"num":0},
	{"id":"19157","name":"Aquiva Gauntlets","icon":"fpsy04hand-et01.png","category":"ARMOR","rarity":"common","probability":0.01,"num":0},
	{"id":"16645","name":"Aquiva Boots","icon":"fpsy04foot-et01.png","category":"ARMOR","rarity":"common","probability":0.01,"num":0},
	{"id":"14120","name":"Seakissed Aquiloop Helmet","icon":"mpsy04cap-et01.png","category":"ARMOR","rarity":"uncommon","probability":0.01,"num":0},
	{"id":"17542","name":"Seakissed Aquiloop Gauntlets","icon":"mpsy04hand-et01.png","category":"ARMOR","rarity":"uncommon","probability":0.01,"num":0},
	{"id":"18373","name":"Seakissed Aquiloop Boots","icon":"mpsy04foot-et01.png","category":"ARMOR","rarity":"uncommon","probability":0.01,"num":0},
	{"id":"13847","name":"Seakissed Aquiva Helmet","icon":"fpsy04cap-et01.png","category":"ARMOR","rarity":"uncommon","probability":0.01,"num":0},
	{"id":"19089","name":"Seakissed Aquiva Gauntlets","icon":"fpsy04hand-et01.png","category":"ARMOR","rarity":"uncommon","probability":0.01,"num":0},
	{"id":"14390","name":"Seakissed Aquiva Boots","icon":"fpsy04foot-et01.png","category":"ARMOR","rarity":"uncommon","probability":0.01,"num":0},
	{"id":"10434","name":"Seerel Helmet","icon":"mrag04cap-et01.png","category":"ARMOR","rarity":"common","probability":0.01,"num":0},
	{"id":"15719","name":"Seerel Gauntlets","icon":"mrag04hand-et01.png","category":"ARMOR","rarity":"common","probability":0.01,"num":0},
	{"id":"13948","name":"Seerel Boots","icon":"mrag04foot-et01.png","category":"ARMOR","rarity":"common","probability":0.01,"num":0},
	{"id":"10671","name":"Seerina Helmet","icon":"frag04cap-et01.png","category":"ARMOR","rarity":"common","probability":0.01,"num":0},
	{"id":"14241","name":"Seerina Gauntlets","icon":"frag04hand-et01.png","category":"ARMOR","rarity":"common","probability":0.01,"num":0},
	{"id":"13252","name":"Seerina Boots","icon":"frag04foot-et01.png","category":"ARMOR","rarity":"common","probability":0.01,"num":0},
	{"id":"19759","name":"Seakissed Seerel Helmet","icon":"mrag04cap-et01.png","category":"ARMOR","rarity":"uncommon","probability":0.01,"num":0},
	{"id":"19056","name":"Seakissed Seerel Gauntlets","icon":"mrag04hand-et01.png","category":"ARMOR","rarity":"uncommon","probability":0.01,"num":0},
	{"id":"17761","name":"Seakissed Seerel Boots","icon":"mrag04foot-et01.png","category":"ARMOR","rarity":"uncommon","probability":0.01,"num":0},
	{"id":"13926","name":"Seakissed Seerina Helmet","icon":"frag04cap-et01.png","category":"ARMOR","rarity":"uncommon","probability":0.01,"num":0},
	{"id":"14325","name":"Seakissed Seerina Gauntlets","icon":"frag04hand-et01.png","category":"ARMOR","rarity":"uncommon","probability":0.01,"num":0},
	{"id":"18888","name":"Seakissed Seerina Boots","icon":"frag04foot-et01.png","category":"ARMOR","rarity":"uncommon","probability":0.01,"num":0},
	{"id":"16959","name":"Marinfury Helmet","icon":"mrin04cap-et01.png","category":"ARMOR","rarity":"common","probability":0.01,"num":0},
	{"id":"15658","name":"Marinfury Gauntlets","icon":"mrin04hand-et01.png","category":"ARMOR","rarity":"common","probability":0.01,"num":0},
	{"id":"12862","name":"Marinfury Boots","icon":"mrin04foot-et01.png","category":"ARMOR","rarity":"common","probability":0.01,"num":0},
	{"id":"17796","name":"Marinflux Helmet","icon":"frin04cap-et01.png","category":"ARMOR","rarity":"common","probability":0.01,"num":0},
	{"id":"17124","name":"Marinflux Gauntlets","icon":"frin04hand-et01.png","category":"ARMOR","rarity":"common","probability":0.01,"num":0},
	{"id":"14983","name":"Marinflux Boots","icon":"frin04foot-et01.png","category":"ARMOR","rarity":"common","probability":0.01,"num":0},
	{"id":"16577","name":"Seakissed Marinfury Helmet","icon":"mrin04cap-et01.png","category":"ARMOR","rarity":"uncommon","probability":0.01,"num":0},
	{"id":"18504","name":"Seakissed Marinfury Gauntlets","icon":"mrin04hand-et01.png","category":"ARMOR","rarity":"uncommon","probability":0.01,"num":0},
	{"id":"17795","name":"Seakissed Marinfury Boots","icon":"mrin04foot-et01.png","category":"ARMOR","rarity":"uncommon","probability":0.01,"num":0},
	{"id":"19717","name":"Seakissed Marinflux Helmet","icon":"frin04cap-et01.png","category":"ARMOR","rarity":"uncommon","probability":0.01,"num":0},
	{"id":"13067","name":"Seakissed Marinflux Gauntlets","icon":"frin04hand-et01.png","category":"ARMOR","rarity":"uncommon","probability":0.01,"num":0},
	{"id":"15280","name":"Seakissed Marinflux Boots","icon":"frin04foot-et01.png","category":"ARMOR","rarity":"uncommon","probability":0.01,"num":0},
	{"id":"16433","name":"Destroyed Coral Shield","icon":"armshihernes-et02.png","category":"ARMOR","rarity":"common","probability":0.01,"num":0},
	{"id":"12651","name":"Mossy Coral Shield","icon":"armshihernes-et01.png","category":"ARMOR","rarity":"uncommon","probability":0.01,"num":0},
	{"id":"12298","name":"Aquanar Suit","icon":"mbil04upper-et01.png","category":"ARMOR","rarity":"common","probability":0.01,"num":0},
	{"id":"19653","name":"Aqualis Suit","icon":"fbil04upper-et01.png","category":"ARMOR","rarity":"common","probability":0.01,"num":0},
	{"id":"14900","name":"Seakissed Aquanar Suit","icon":"mbil04upper-et01.png","category":"ARMOR","rarity":"uncommon","probability":0.01,"num":0},
	{"id":"14858","name":"Seakissed Aqualis Suit","icon":"fbil04upper-et01.png","category":"ARMOR","rarity":"uncommon","probability":0.01,"num":0},
	{"id":"15228","name":"Marinthor Suit","icon":"mbla04upper-et01.png","category":"ARMOR","rarity":"common","probability":0.01,"num":0},
	{"id":"19465","name":"Marinva Suit","icon":"fbla04upper-et01.png","category":"ARMOR","rarity":"common","probability":0.01,"num":0},
	{"id":"14888","name":"Seakissed Marinthor Suit","icon":"mbla04upper-et01.png","category":"ARMOR","rarity":"uncommon","probability":0.01,"num":0},
	{"id":"12504","name":"Seakissed Marinva Suit","icon":"fbla04upper-et01.png","category":"ARMOR","rarity":"uncommon","probability":0.01,"num":0},
	{"id":"13044","name":"Sealith Suit","icon":"mele04upper-et01.png","category":"ARMOR","rarity":"common","probability":0.01,"num":0},
	{"id":"16299","name":"Seavara Suit","icon":"fele04upper-et01.png","category":"ARMOR","rarity":"common","probability":0.01,"num":0},
	{"id":"11104","name":"Seakissed Sealith Suit","icon":"mele04upper-et01.png","category":"ARMOR","rarity":"uncommon","probability":0.01,"num":0},
	{"id":"1324","name":"Seakissed Seavara Suit","icon":"fele04upper-et01.png","category":"ARMOR","rarity":"uncommon","probability":0.01,"num":0},
	{"id":"17239","name":"Brinex Suit","icon":"mjst04upper-et01.png","category":"ARMOR","rarity":"common","probability":0.01,"num":0},
	{"id":"19853","name":"Brineya Suit","icon":"fjst04upper-et01.png","category":"ARMOR","rarity":"common","probability":0.01,"num":0},
	{"id":"12358","name":"Seakissed Brinex Suit","icon":"mjst04upper-et01.png","category":"ARMOR","rarity":"uncommon","probability":0.01,"num":0},
	{"id":"19207","name":"Seakissed Brineya Suit","icon":"fjst04upper-et01.png","category":"ARMOR","rarity":"uncommon","probability":0.01,"num":0},
	{"id":"10397","name":"Tidewhis Suit","icon":"mkin04upper-et01.png","category":"ARMOR","rarity":"common","probability":0.01,"num":0},
	{"id":"16101","name":"Tidera Suit","icon":"fkin04upper-et01.png","category":"ARMOR","rarity":"common","probability":0.01,"num":0},
	{"id":"6901","name":"Seakissed Tidewhis Suit","icon":"mkin04upper-et01.png","category":"ARMOR","rarity":"uncommon","probability":0.01,"num":0},
	{"id":"16321","name":"Seakissed Tidera Suit","icon":"fkin04upper-et01.png","category":"ARMOR","rarity":"uncommon","probability":0.01,"num":0},
	{"id":"19979","name":"Aquiloop Suit","icon":"mpsy04upper-et01.png","category":"ARMOR","rarity":"common","probability":0.01,"num":0},
	{"id":"14249","name":"Aquiva Suit","icon":"fpsy04upper-et01.png","category":"ARMOR","rarity":"common","probability":0.01,"num":0},
	{"id":"14185","name":"Seakissed Aquiloop Suit","icon":"mpsy04upper-et01.png","category":"ARMOR","rarity":"uncommon","probability":0.01,"num":0},
	{"id":"18740","name":"Seakissed Aquiva Suit","icon":"fpsy04upper-et01.png","category":"ARMOR","rarity":"uncommon","probability":0.01,"num":0},
	{"id":"14738","name":"Seerel Suit","icon":"mrag04upper-et01.png","category":"ARMOR","rarity":"common","probability":0.01,"num":0},
	{"id":"17096","name":"Seerina Suit","icon":"frag04upper-et01.png","category":"ARMOR","rarity":"common","probability":0.01,"num":0},
	{"id":"12536","name":"Seakissed Seerel Suit","icon":"mrag04upper-et01.png","category":"ARMOR","rarity":"uncommon","probability":0.01,"num":0},
	{"id":"11186","name":"Seakissed Seerina Suit","icon":"frag04upper-et01.png","category":"ARMOR","rarity":"uncommon","probability":0.01,"num":0},
	{"id":"17559","name":"Marinfury Suit","icon":"mrin04upper-et01.png","category":"ARMOR","rarity":"common","probability":0.01,"num":0},
	{"id":"18223","name":"Marinflux Suit","icon":"frin04upper-et01.png","category":"ARMOR","rarity":"common","probability":0.01,"num":0},
	{"id":"18567","name":"Seakissed Marinfury Suit","icon":"mrin04upper-et01.png","category":"ARMOR","rarity":"uncommon","probability":0.01,"num":0},
	{"id":"16184","name":"Seakissed Marinflux Suit","icon":"frin04upper-et01.png","category":"ARMOR","rarity":"uncommon","probability":0.01,"num":0},
	{"id":"6844","name":"4点精炼骰子","icon":"genmatdiefour.png","category":"MATERIAL","rarity":"uncommon","probability":0.01,"num":0},
	{"id":"1250","name":"6点精炼骰子","icon":"genmatdiesix.png","category":"MATERIAL","rarity":"uncommon","probability":0.01,"num":0},
	{"id":"1764","name":"敏捷戒指","icon":"genjewrinnorrin03.png","category":"JEWELRY","rarity":"uncommon","probability":0.01,"num":0},
	{"id":"1371","name":"电磁卡片","icon":"genmateleeletri.png","category":"MATERIAL","rarity":"common","probability":0.01,"num":0},
	{"id":"5455","name":"闪电卡片","icon":"genmateleeletri.png","category":"MATERIAL","rarity":"common","probability":0.01,"num":0},
	{"id":"8600","name":"宠物蛋","icon":"petegg.png","category":"RAISEDPET","rarity":"common","probability":0.01,"num":0},
	{"id":"2811","name":"火属性装备卡片(3%) ","icon":"genmateleflame.png","category":"MATERIAL","rarity":"common","probability":0.01,"num":0},
	{"id":"6439","name":"水属性装备卡片(3%)","icon":"genmateleriver.png","category":"MATERIAL","rarity":"common","probability":0.01,"num":0},
	{"id":"5788","name":"风属性装备卡片(3%)","icon":"genmatelecyclon.png","category":"MATERIAL","rarity":"common","probability":0.01,"num":0},
	{"id":"5545","name":"雷属性装备卡片(3%)","icon":"genmatelegenerator.png","category":"MATERIAL","rarity":"common","probability":0.01,"num":0},
	{"id":"6242","name":"土属性装备卡片(3%)","icon":"genmateledesert.png","category":"MATERIAL","rarity":"common","probability":0.01,"num":0},
	{"id":"12908","name":"Shining Oricalkum","icon":"genmatorichalcum02.png","category":"MATERIAL","rarity":"veryrare","probability":0.01,"num":0},
	{"id":"7207","name":"火焰卡片","icon":"genmatelefire.png","category":"MATERIAL","rarity":"common","probability":0.01,"num":0},
	{"id":"7659","name":"湖泊卡片","icon":"genmatelewater.png","category":"MATERIAL","rarity":"common","probability":0.01,"num":0},
	{"id":"9399","name":"巨石卡片","icon":"genmateleearth.png","category":"MATERIAL","rarity":"common","probability":0.01,"num":0},
	{"id":"2781","name":"大风卡片","icon":"genmatelewind.png","category":"MATERIAL","rarity":"common","probability":0.01,"num":0},
	{"id":"3687","name":"烈火卡片","icon":"genmatelefire.png","category":"MATERIAL","rarity":"common","probability":0.01,"num":0},
	{"id":"3830","name":"河流卡片","icon":"genmatelewater.png","category":"MATERIAL","rarity":"common","probability":0.01,"num":0},
	{"id":"6385","name":"沙漠卡片","icon":"genmateleearth.png","category":"MATERIAL","rarity":"common","probability":0.01,"num":0},
	{"id":"5049","name":"旋风卡片","icon":"genmatelewind.png","category":"MATERIAL","rarity":"common","probability":0.01,"num":0},
	{"id":"107","name":"火属性装备卡片(2%)","icon":"genmateleflame.png","category":"MATERIAL","rarity":"common","probability":0.001,"num":0},
	{"id":"1159","name":"水属性装备卡片(2%)","icon":"genmateleriver.png","category":"MATERIAL","rarity":"common","probability":0.001,"num":0},
	{"id":"14","name":"风属性装备卡片(2%)","icon":"genmatelecyclon.png","category":"MATERIAL","rarity":"common","probability":0.001,"num":0},
	{"id":"7559","name":"雷属性装备卡片(2%)","icon":"genmatelegenerator.png","category":"MATERIAL","rarity":"common","probability":0.001,"num":0},
	{"id":"8926","name":"土属性装备卡片(2%)","icon":"genmateledesert.png","category":"MATERIAL","rarity":"common","probability":0.001,"num":0},
	{"id":"19938","name":"Destroyed Nautilus","icon":"weaaxehernes-et02.png","category":"WEAPON","rarity":"common","probability":0.001,"num":0},
	{"id":"9878","name":"Neglected Nautilus","icon":"weaaxehernes-et01.png","category":"WEAPON","rarity":"uncommon","probability":0.001,"num":0},
	{"id":"15243","name":"Destroyed Nemo's Fury","icon":"weabowhernes-et02.png","category":"WEAPON","rarity":"common","probability":0.001,"num":0},
	{"id":"10350","name":"Nebulous Nemo's Fury","icon":"weabowhernes-et01.png","category":"WEAPON","rarity":"uncommon","probability":0.001,"num":0},
	{"id":"15828","name":"Destroyed Fist of Tides","icon":"weaknuhernes-et02.png","category":"WEAPON","rarity":"common","probability":0.001,"num":0},
	{"id":"13740","name":"Flawed Fist of Tides","icon":"weaknuhernes-et01.png","category":"WEAPON","rarity":"uncommon","probability":0.001,"num":0},
	{"id":"17776","name":"Destroyed Conch Stave","icon":"weastahernes-et02.png","category":"WEAPON","rarity":"common","probability":0.001,"num":0},
	{"id":"11615","name":"Craggy Conch Stave","icon":"weastahernes-et01.png","category":"WEAPON","rarity":"uncommon","probability":0.001,"num":0},
	{"id":"17809","name":"Destroyed Song of Sirens","icon":"weachehernes-et02.png","category":"WEAPON","rarity":"common","probability":0.001,"num":0},
	{"id":"14191","name":"Sundered Song of Sirens","icon":"weachehernes-et01.png","category":"WEAPON","rarity":"uncommon","probability":0.001,"num":0},
	{"id":"15597","name":"Destroyed Coral Cutlass","icon":"weaswdhernes-et02.png","category":"WEAPON","rarity":"common","probability":0.001,"num":0},
	{"id":"14510","name":"Crumbling Coral Cutlass","icon":"weaswdhernes-et01.png","category":"WEAPON","rarity":"uncommon","probability":0.001,"num":0},
	{"id":"3903","name":"Destroyed Lamprey's Wand","icon":"weawanhernes-et02.png","category":"WEAPON","rarity":"common","probability":0.001,"num":0},
	{"id":"19430","name":"Leaky Lamprey's Wand","icon":"weawanhernes-et01.png","category":"WEAPON","rarity":"uncommon","probability":0.001,"num":0},
	{"id":"4152","name":"Destroyed Typhoon","icon":"weayoyhernes-et02.png","category":"WEAPON","rarity":"common","probability":0.001,"num":0},
	{"id":"18759","name":"Tarnished Typhoon","icon":"weayoyhernes-et01.png","category":"WEAPON","rarity":"uncommon","probability":0.001,"num":0},
	{"id":"16742","name":"Destroyed Abyss","icon":"weaaxthernes-et02.png","category":"WEAPON","rarity":"common","probability":0.001,"num":0},
	{"id":"12811","name":"Archaic Abyss","icon":"weaaxthernes-et01.png","category":"WEAPON","rarity":"uncommon","probability":0.001,"num":0},
	{"id":"16978","name":"Destroyed Leviathan","icon":"weaswthernes-et02.png","category":"WEAPON","rarity":"common","probability":0.001,"num":0},
	{"id":"14556","name":"Lethargic Leviathan","icon":"weaswthernes-et01.png","category":"WEAPON","rarity":"uncommon","probability":0.001,"num":0},
	{"id":"9344","name":"10点精炼骰子","icon":"genmatdieten.png","category":"MATERIAL","rarity":"veryrare","probability":0.001,"num":0},
	{"id":"7178","name":"白银耳环","icon":"genjewearnorear01.png","category":"JEWELRY","rarity":"uncommon","probability":0.001,"num":0},
	{"id":"6803","name":"生命女神项链","icon":"genjewnecnornec01.png","category":"JEWELRY","rarity":"uncommon","probability":0.001,"num":0},
	{"id":"8646","name":"活力之源项链","icon":"genjewnecnornec03.png","category":"JEWELRY","rarity":"uncommon","probability":0.001,"num":0},
	{"id":"9233","name":"魔力之源项链","icon":"genjewnecnornec02.png","category":"JEWELRY","rarity":"uncommon","probability":0.001,"num":0},
	{"id":"5536","name":"力量戒指","icon":"genjewrinnorrin01.png","category":"JEWELRY","rarity":"uncommon","probability":0.001,"num":0},
	{"id":"2064","name":"智力戒指","icon":"genjewrinnorrin02.png","category":"JEWELRY","rarity":"uncommon","probability":0.001,"num":0},
	{"id":"6531","name":"体质戒指","icon":"genjewrinnorrin04.png","category":"JEWELRY","rarity":"uncommon","probability":0.001,"num":0},
	{"id":"4635","name":"火属性装备卡片(4%)","icon":"genmateleflame.png","category":"MATERIAL","rarity":"rare","probability":0.001,"num":0},
	{"id":"4126","name":"水属性装备卡片(4%)","icon":"genmateleriver.png","category":"MATERIAL","rarity":"rare","probability":0.001,"num":0},
	{"id":"5945","name":"风属性装备卡片(4%)","icon":"genmatelecyclon.png","category":"MATERIAL","rarity":"rare","probability":0.001,"num":0},
	{"id":"8243","name":"雷属性装备卡片(4%)","icon":"genmatelegenerator.png","category":"MATERIAL","rarity":"rare","probability":0.001,"num":0},
	{"id":"7436","name":"土属性装备卡片(4%)","icon":"genmateledesert.png","category":"MATERIAL","rarity":"rare","probability":0.001,"num":0},
	{"id":"15281","name":"Roelayne Helmet","icon":"fbilset06cap.png","category":"ARMOR","rarity":"veryrare","probability":0.0001,"num":0},
	{"id":"12905","name":"Roelayne Boots","icon":"fbilset06foot.png","category":"ARMOR","rarity":"veryrare","probability":0.0001,"num":0},
	{"id":"12611","name":"Roenier Helmet","icon":"mbilset06cap.png","category":"ARMOR","rarity":"veryrare","probability":0.0001,"num":0},
	{"id":"19083","name":"Roenier Boots","icon":"mbilset06foot.png","category":"ARMOR","rarity":"veryrare","probability":0.0001,"num":0},
	{"id":"11315","name":"Herainn Helmet","icon":"fblaset06cap.png","category":"ARMOR","rarity":"veryrare","probability":0.0001,"num":0},
	{"id":"10690","name":"Herainn Boots","icon":"fblaset06foot.png","category":"ARMOR","rarity":"veryrare","probability":0.0001,"num":0},
	{"id":"18304","name":"Heraud Helmet","icon":"mblaset06cap.png","category":"ARMOR","rarity":"veryrare","probability":0.0001,"num":0},
	{"id":"12031","name":"Heraud Boots","icon":"mblaset06foot.png","category":"ARMOR","rarity":"veryrare","probability":0.0001,"num":0},
	{"id":"10199","name":"Lypine Helmet","icon":"feleset06cap.png","category":"ARMOR","rarity":"veryrare","probability":0.0001,"num":0},
	{"id":"13492","name":"Lypine Boots","icon":"feleset06foot.png","category":"ARMOR","rarity":"veryrare","probability":0.0001,"num":0},
	{"id":"14731","name":"Lippin Helmet","icon":"meleset06cap.png","category":"ARMOR","rarity":"veryrare","probability":0.0001,"num":0},
	{"id":"18383","name":"Lippin Boots","icon":"meleset06foot.png","category":"ARMOR","rarity":"veryrare","probability":0.0001,"num":0},
	{"id":"13895","name":"Curena Helmet","icon":"fjstset06cap.png","category":"ARMOR","rarity":"veryrare","probability":0.0001,"num":0},
	{"id":"16091","name":"Curena Boots","icon":"fjstset06foot.png","category":"ARMOR","rarity":"veryrare","probability":0.0001,"num":0},
	{"id":"11056","name":"Curio Helmet","icon":"mjstset06cap.png","category":"ARMOR","rarity":"veryrare","probability":0.0001,"num":0},
	{"id":"11660","name":"Curio Boots","icon":"mjstset06foot.png","category":"ARMOR","rarity":"veryrare","probability":0.0001,"num":0},
	{"id":"17314","name":"Bilari Helmet","icon":"fkinset06cap.png","category":"ARMOR","rarity":"veryrare","probability":0.0001,"num":0},
	{"id":"15185","name":"Bilari Boots","icon":"fkinset06foot.png","category":"ARMOR","rarity":"veryrare","probability":0.0001,"num":0},
	{"id":"15033","name":"Bileire Helmet","icon":"mkinset06cap.png","category":"ARMOR","rarity":"veryrare","probability":0.0001,"num":0},
	{"id":"10107","name":"Bileire Boots","icon":"mkinset06foot.png","category":"ARMOR","rarity":"veryrare","probability":0.0001,"num":0},
	{"id":"14123","name":"Rephira Helmet","icon":"fpsyset06cap.png","category":"ARMOR","rarity":"veryrare","probability":0.0001,"num":0},
	{"id":"16631","name":"Rephira Boots","icon":"fpsyset06foot.png","category":"ARMOR","rarity":"veryrare","probability":0.0001,"num":0},
	{"id":"16951","name":"Reffiro Helmet","icon":"mpsyset06cap.png","category":"ARMOR","rarity":"veryrare","probability":0.0001,"num":0},
	{"id":"19049","name":"Reffiro Boots","icon":"mpsyset06foot.png","category":"ARMOR","rarity":"veryrare","probability":0.0001,"num":0},
	{"id":"17385","name":"Hanira Helmet","icon":"fragset06cap.png","category":"ARMOR","rarity":"veryrare","probability":0.0001,"num":0},
	{"id":"1449","name":"Hanira Boots","icon":"fragset06foot.png","category":"ARMOR","rarity":"veryrare","probability":0.0001,"num":0},
	{"id":"14703","name":"Hainure Helmet","icon":"mragset06cap.png","category":"ARMOR","rarity":"veryrare","probability":0.0001,"num":0},
	{"id":"19245","name":"Hainure Boots","icon":"mragset06foot.png","category":"ARMOR","rarity":"veryrare","probability":0.0001,"num":0},
	{"id":"13440","name":"Rayne Helmet","icon":"frinset06cap.png","category":"ARMOR","rarity":"veryrare","probability":0.0001,"num":0},
	{"id":"14531","name":"Rayne Boots","icon":"frinset06foot.png","category":"ARMOR","rarity":"veryrare","probability":0.0001,"num":0},
	{"id":"10901","name":"Reine Helmet","icon":"mrinset06cap.png","category":"ARMOR","rarity":"veryrare","probability":0.0001,"num":0},
	{"id":"13210","name":"Reine Boots","icon":"mrinset06foot.png","category":"ARMOR","rarity":"veryrare","probability":0.0001,"num":0},
	{"id":"15838","name":"Roelayne Gauntlets","icon":"fbilset06hand.png","category":"ARMOR","rarity":"veryrare","probability":0.0001,"num":0},
	{"id":"19460","name":"Roenier Gauntlets","icon":"mbilset06hand.png","category":"ARMOR","rarity":"veryrare","probability":0.0001,"num":0},
	{"id":"16334","name":"Herainn Gauntlets","icon":"fblaset06hand.png","category":"ARMOR","rarity":"veryrare","probability":0.0001,"num":0},
	{"id":"14319","name":"Heraud Gauntlets","icon":"mblaset06hand.png","category":"ARMOR","rarity":"veryrare","probability":0.0001,"num":0},
	{"id":"15562","name":"Lypine Gauntlets","icon":"feleset06hand.png","category":"ARMOR","rarity":"veryrare","probability":0.0001,"num":0},
	{"id":"13737","name":"Lippin Gauntlets","icon":"meleset06hand.png","category":"ARMOR","rarity":"veryrare","probability":0.0001,"num":0},
	{"id":"11294","name":"Curena Gauntlets","icon":"fjstset06hand.png","category":"ARMOR","rarity":"veryrare","probability":0.0001,"num":0},
	{"id":"13899","name":"Curio Gauntlets","icon":"mjstset06hand.png","category":"ARMOR","rarity":"veryrare","probability":0.0001,"num":0},
	{"id":"17243","name":"Bilari Gauntlets","icon":"fkinset06hand.png","category":"ARMOR","rarity":"veryrare","probability":0.0001,"num":0},
	{"id":"13560","name":"Bileire Gauntlets","icon":"mkinset06hand.png","category":"ARMOR","rarity":"veryrare","probability":0.0001,"num":0},
	{"id":"17310","name":"Rephira Gauntlets","icon":"fpsyset06hand.png","category":"ARMOR","rarity":"veryrare","probability":0.0001,"num":0},
	{"id":"11344","name":"Reffiro Gauntlets","icon":"mpsyset06hand.png","category":"ARMOR","rarity":"veryrare","probability":0.0001,"num":0},
	{"id":"5730","name":"Hanira Gauntlets","icon":"fragset06hand.png","category":"ARMOR","rarity":"veryrare","probability":0.0001,"num":0},
	{"id":"19182","name":"Hainure Gauntlets","icon":"mragset06hand.png","category":"ARMOR","rarity":"veryrare","probability":0.0001,"num":0},
	{"id":"15988","name":"Rayne Gauntlets","icon":"frinset06hand.png","category":"ARMOR","rarity":"veryrare","probability":0.0001,"num":0},
	{"id":"13658","name":"Reine Gauntlets","icon":"mrinset06hand.png","category":"ARMOR","rarity":"veryrare","probability":0.0001,"num":0},
	{"id":"6672","name":"12点精炼骰子","icon":"genmatdietwelve.png","category":"MATERIAL","rarity":"veryrare","probability":0.0001,"num":0},
	{"id":"18057","name":"Coral Shield","icon":"armshihernes.png","category":"ARMOR","rarity":"rare","probability":0.0001,"num":0},
	{"id":"13570","name":"Roelayne Suit","icon":"fbilset06upper.png","category":"ARMOR","rarity":"veryrare","probability":0.0001,"num":0},
	{"id":"17353","name":"Roenier Suit","icon":"mbilset06upper.png","category":"ARMOR","rarity":"veryrare","probability":0.0001,"num":0},
	{"id":"16409","name":"Herainn Suit","icon":"fblaset06upper.png","category":"ARMOR","rarity":"veryrare","probability":0.0001,"num":0},
	{"id":"16799","name":"Heraud Suit","icon":"mblaset06upper.png","category":"ARMOR","rarity":"veryrare","probability":0.0001,"num":0},
	{"id":"18487","name":"Lypine Suit","icon":"feleset06upper.png","category":"ARMOR","rarity":"veryrare","probability":0.0001,"num":0},
	{"id":"11696","name":"Lippin Suit","icon":"meleset06upper.png","category":"ARMOR","rarity":"veryrare","probability":0.0001,"num":0},
	{"id":"16423","name":"Curena Suit","icon":"fjstset06upper.png","category":"ARMOR","rarity":"veryrare","probability":0.0001,"num":0},
	{"id":"16059","name":"Curio Suit","icon":"mjstset06upper.png","category":"ARMOR","rarity":"veryrare","probability":0.0001,"num":0},
	{"id":"15332","name":"Bilari Suit","icon":"fkinset06upper.png","category":"ARMOR","rarity":"veryrare","probability":0.0001,"num":0},
	{"id":"19474","name":"Bileire Suit","icon":"mkinset06upper.png","category":"ARMOR","rarity":"veryrare","probability":0.0001,"num":0},
	{"id":"12584","name":"Rephira Suit","icon":"fpsyset06upper.png","category":"ARMOR","rarity":"veryrare","probability":0.0001,"num":0},
	{"id":"13731","name":"Reffiro Suit","icon":"mpsyset06upper.png","category":"ARMOR","rarity":"veryrare","probability":0.0001,"num":0},
	{"id":"12396","name":"Hanira Suit","icon":"fragset06upper.png","category":"ARMOR","rarity":"veryrare","probability":0.0001,"num":0},
	{"id":"11849","name":"Hainure Suit ","icon":"mragset06upper.png","category":"ARMOR","rarity":"veryrare","probability":0.0001,"num":0},
	{"id":"19929","name":"Rayne Suit","icon":"frinset06upper.png","category":"ARMOR","rarity":"veryrare","probability":0.0001,"num":0},
	{"id":"16051","name":"Reine Suit","icon":"mrinset06upper.png","category":"ARMOR","rarity":"veryrare","probability":0.0001,"num":0},
	{"id":"10319","name":"珊瑚短剑","icon":"weaswdhernes.png","category":"WEAPON","rarity":"unique","probability":0.0001,"num":0},
	{"id":"19897","name":"螺号","icon":"weaaxehernes.png","category":"WEAPON","rarity":"unique","probability":0.0001,"num":0},
	{"id":"16014","name":"怒涛","icon":"weabowhernes.png","category":"WEAPON","rarity":"unique","probability":0.0001,"num":0},
	{"id":"14971","name":"潮汐之拳","icon":"weaknuhernes.png","category":"WEAPON","rarity":"unique","probability":0.0001,"num":0},
	{"id":"14000","name":"海潮回响","icon":"weastahernes.png","category":"WEAPON","rarity":"unique","probability":0.0001,"num":0},
	{"id":"16918","name":"塞壬之歌","icon":"weachehernes.png","category":"WEAPON","rarity":"unique","probability":0.0001,"num":0},
	{"id":"14402","name":"绝渊","icon":"weaaxthernes.png","category":"WEAPON","rarity":"unique","probability":0.0001,"num":0},
	{"id":"13811","name":"猛兽","icon":"weaswthernes.png","category":"WEAPON","rarity":"unique","probability":0.0001,"num":0},
	{"id":"13845","name":"呼风唤雨","icon":"weawanhernes.png","category":"WEAPON","rarity":"unique","probability":0.0001,"num":0},
	{"id":"13024","name":"涡旋","icon":"weayoyhernes.png","category":"WEAPON","rarity":"unique","probability":0.0001,"num":0}
]
let boss_drop = [
	// 8-14个
	{"id":"19291","name":"被诅咒的首饰碎片","icon":"syssysscrscrapgarnet.png","category":"MATERIAL","rarity":"common","probability":1.00,"num":0},
	{"id":"7867","name":"8点精炼骰子","icon":"genmatdieeight.png","category":"MATERIAL","rarity":"uncommon","probability":0.60,"num":0},
	{"id":"1250","name":"6点精炼骰子","icon":"genmatdiesix.png","category":"MATERIAL","rarity":"uncommon","probability":0.60,"num":0},
	{"id":"6844","name":"4点精炼骰子","icon":"genmatdiefour.png","category":"MATERIAL","rarity":"uncommon","probability":0.60,"num":0},
	{"id":"6234","name":"终极魔力多","icon":"genpotrefr10.png","category":"RECOVERY","rarity":"common","probability":0.30,"num":0},
	{"id":"4503","name":"海鲜披萨","icon":"genfoocoopizza.png","category":"RECOVERY","rarity":"common","probability":0.30,"num":0},
	{"id":"3880","name":"活力饮料900","icon":"genpotdrivithig3.png","category":"RECOVERY","rarity":"common","probability":0.30,"num":0},
	{"id":"2311","name":"解毒剂","icon":"genpotantido.png","category":"BUFF","rarity":"common","probability":0.30,"num":0},
	{"id":"2347","name":"宠物笼钥匙(高级)","icon":"treasuregoldenkey.png","category":"MATERIAL","rarity":"veryrare","probability":0.20,"num":0},
	{"id":"1200","name":"黄水晶","icon":"gengemyellowcrystal.png","category":"BOOTY","rarity":"common","probability":0.10,"num":0},
	{"id":"6089","name":"绿水晶","icon":"gengemgreencrystal.png","category":"BOOTY","rarity":"common","probability":0.10,"num":0},
	{"id":"2662","name":"奇怪的象牙","icon":"gengemganesaivory.png","category":"BOOTY","rarity":"common","probability":0.10,"num":0},
	{"id":"218","name":"蓝水晶","icon":"gengembluecrystal.png","category":"BOOTY","rarity":"common","probability":0.10,"num":0},
	{"id":"2415","name":"金属之心","icon":"gengemasuraheart.png","category":"BOOTY","rarity":"common","probability":0.10,"num":0},
	{"id":"19384","name":"Broken Wings","icon":"gengembrokenwings.png","category":"BOOTY","rarity":"common","probability":0.10,"num":0},
	{"id":"18576","name":"Sharp Canine","icon":"gengemcaninetooth.png","category":"BOOTY","rarity":"common","probability":0.10,"num":0},
	{"id":"11763","name":"Gogloo","icon":"gengemgoggloo.png","category":"BOOTY","rarity":"common","probability":0.10,"num":0},
	{"id":"18478","name":"Big Nippers","icon":"gengemgiantforceps.png","category":"BOOTY","rarity":"common","probability":0.10,"num":0},
	{"id":"18282","name":"Crab Shell","icon":"gengemcarapace.png","category":"BOOTY","rarity":"common","probability":0.10,"num":0},
	{"id":"14421","name":"Crumbly Hair","icon":"gengemcrisphair.png","category":"BOOTY","rarity":"common","probability":0.10,"num":0},
	{"id":"10377","name":"Great Crown","icon":"gengemgreatcrown.png","category":"BOOTY","rarity":"common","probability":0.10,"num":0},
	{"id":"10896","name":"Keen Tooth","icon":"gengemsharptooth.png","category":"BOOTY","rarity":"common","probability":0.10,"num":0},
	{"id":"10779","name":"Ink Pouch","icon":"gengeminksac.png","category":"BOOTY","rarity":"common","probability":0.10,"num":0},
	{"id":"9344","name":"10点精炼骰子","icon":"genmatdieten.png","category":"MATERIAL","rarity":"veryrare","probability":0.05,"num":0},
	{"id":"1932","name":"火焰卡片(B)","icon":"genmatelecandle.png","category":"MATERIAL","rarity":"veryrare","probability":0.05,"num":0},
	{"id":"637","name":"流水卡片(B)","icon":"genmatelerainatk.png","category":"MATERIAL","rarity":"veryrare","probability":0.05,"num":0},
	{"id":"8515","name":"暴风卡片(B)","icon":"genmatelebreezeatk.png","category":"MATERIAL","rarity":"veryrare","probability":0.05,"num":0},
	{"id":"8810","name":"雷电卡片(B)","icon":"genmatelesparkatk.png","category":"MATERIAL","rarity":"veryrare","probability":0.05,"num":0},
	{"id":"6434","name":"岩石卡片(B)","icon":"genmatelesandatk.png","category":"MATERIAL","rarity":"veryrare","probability":0.05,"num":0},
	{"id":"7851","name":"岩浆卡片(B)","icon":"genmatelelavaatk.png","category":"MATERIAL","rarity":"veryrare","probability":0.05,"num":0},
	{"id":"5577","name":"电伏卡片(B)","icon":"genmatelevoltatk.png","category":"MATERIAL","rarity":"veryrare","probability":0.05,"num":0},
	{"id":"4353","name":"荆棘卡片(B)","icon":"genmatelethorn.png","category":"MATERIAL","rarity":"veryrare","probability":0.05,"num":0},
	{"id":"15403","name":"晶石","icon":"genmatorichalcum01.png","category":"MATERIAL","rarity":"veryrare","probability":0.05,"num":0},
	{"id":"6672","name":"12点精炼骰子","icon":"genmatdietwelve.png","category":"MATERIAL","rarity":"veryrare","probability":0.05,"num":0},
	{"id":"3153","name":"火焰卡片(C)","icon":"genmatelecandle.png","category":"MATERIAL","rarity":"veryrare","probability":0.02,"num":0},
	{"id":"6605","name":"流水卡片(C)","icon":"genmatelerainatk.png","category":"MATERIAL","rarity":"veryrare","probability":0.02,"num":0},
	{"id":"6833","name":"暴风卡片(C)","icon":"genmatelebreezeatk.png","category":"MATERIAL","rarity":"veryrare","probability":0.02,"num":0},
	{"id":"2799","name":"雷电卡片(C)","icon":"genmatelesparkatk.png","category":"MATERIAL","rarity":"veryrare","probability":0.02,"num":0},
	{"id":"7382","name":"岩石卡片(C)","icon":"genmatelesandatk.png","category":"MATERIAL","rarity":"veryrare","probability":0.02,"num":0},
	{"id":"5074","name":"岩浆卡片(C)","icon":"genmatelelavaatk.png","category":"MATERIAL","rarity":"veryrare","probability":0.02,"num":0},
	{"id":"5681","name":"电伏卡片(C)","icon":"genmatelevoltatk.png","category":"MATERIAL","rarity":"veryrare","probability":0.02,"num":0},
	{"id":"2731","name":"荆棘卡片(C)","icon":"genmatelethorn.png","category":"MATERIAL","rarity":"veryrare","probability":0.02,"num":0},
	{"id":"4095","name":"Aquanar Helmet","icon":"mbil04cap-et01.png","category":"ARMOR","rarity":"common","probability":0.01,"num":0},
	{"id":"12298","name":"Aquanar Suit","icon":"mbil04upper-et01.png","category":"ARMOR","rarity":"common","probability":0.01,"num":0},
	{"id":"12332","name":"Aquanar Gauntlets","icon":"mbil04hand-et01.png","category":"ARMOR","rarity":"common","probability":0.01,"num":0},
	{"id":"15862","name":"Aquanar Boots","icon":"mbil04foot-et01.png","category":"ARMOR","rarity":"common","probability":0.01,"num":0},
	{"id":"16124","name":"Aqualis Helmet","icon":"fbil04cap-et01.png","category":"ARMOR","rarity":"common","probability":0.01,"num":0},
	{"id":"19653","name":"Aqualis Suit","icon":"fbil04upper-et01.png","category":"ARMOR","rarity":"common","probability":0.01,"num":0},
	{"id":"11650","name":"Aqualis Gauntlets","icon":"fbil04hand-et01.png","category":"ARMOR","rarity":"common","probability":0.01,"num":0},
	{"id":"18535","name":"Aqualis Boots","icon":"fbil04foot-et01.png","category":"ARMOR","rarity":"common","probability":0.01,"num":0},
	{"id":"10967","name":"Seakissed Aquanar Helmet","icon":"mbil04cap-et01.png","category":"ARMOR","rarity":"uncommon","probability":0.01,"num":0},
	{"id":"14900","name":"Seakissed Aquanar Suit","icon":"mbil04upper-et01.png","category":"ARMOR","rarity":"uncommon","probability":0.01,"num":0},
	{"id":"17563","name":"Seakissed Aquanar Gauntlets","icon":"mbil04hand-et01.png","category":"ARMOR","rarity":"uncommon","probability":0.01,"num":0},
	{"id":"18147","name":"Seakissed Aquanar Boots","icon":"mbil04foot-et01.png","category":"ARMOR","rarity":"uncommon","probability":0.01,"num":0},
	{"id":"19079","name":"Seakissed Aqualis Helmet","icon":"fbil04cap-et01.png","category":"ARMOR","rarity":"uncommon","probability":0.01,"num":0},
	{"id":"14858","name":"Seakissed Aqualis Suit","icon":"fbil04upper-et01.png","category":"ARMOR","rarity":"uncommon","probability":0.01,"num":0},
	{"id":"18008","name":"Seakissed Aqualis Gauntlets","icon":"fbil04hand-et01.png","category":"ARMOR","rarity":"uncommon","probability":0.01,"num":0},
	{"id":"16467","name":"Seakissed Aqualis Boots","icon":"fbil04foot-et01.png","category":"ARMOR","rarity":"uncommon","probability":0.01,"num":0},
	{"id":"10725","name":"Marinthor Helmet","icon":"mbla04cap-et01.png","category":"ARMOR","rarity":"common","probability":0.01,"num":0},
	{"id":"15228","name":"Marinthor Suit","icon":"mbla04upper-et01.png","category":"ARMOR","rarity":"common","probability":0.01,"num":0},
	{"id":"19923","name":"Marinthor Gauntlets","icon":"mbla04hand-et01.png","category":"ARMOR","rarity":"common","probability":0.01,"num":0},
	{"id":"14283","name":"Marinthor Boots","icon":"mbla04foot-et01.png","category":"ARMOR","rarity":"common","probability":0.01,"num":0},
	{"id":"16660","name":"Marinva Helmet","icon":"fbla04cap-et01.png","category":"ARMOR","rarity":"common","probability":0.01,"num":0},
	{"id":"19465","name":"Marinva Suit","icon":"fbla04upper-et01.png","category":"ARMOR","rarity":"common","probability":0.01,"num":0},
	{"id":"18685","name":"Marinva Gauntlets","icon":"fbla04hand-et01.png","category":"ARMOR","rarity":"common","probability":0.01,"num":0},
	{"id":"16640","name":"Marinva Boots","icon":"fbla04foot-et01.png","category":"ARMOR","rarity":"common","probability":0.01,"num":0},
	{"id":"17832","name":"Seakissed Marinthor Helmet","icon":"mbla04cap-et01.png","category":"ARMOR","rarity":"uncommon","probability":0.01,"num":0},
	{"id":"14888","name":"Seakissed Marinthor Suit","icon":"mbla04upper-et01.png","category":"ARMOR","rarity":"uncommon","probability":0.01,"num":0},
	{"id":"10275","name":"Seakissed Marinthor Gauntlets","icon":"mbla04hand-et01.png","category":"ARMOR","rarity":"uncommon","probability":0.01,"num":0},
	{"id":"17503","name":"Seakissed Marinthor Boots","icon":"mbla04foot-et01.png","category":"ARMOR","rarity":"uncommon","probability":0.01,"num":0},
	{"id":"18098","name":"Seakissed Marinva Helmet","icon":"fbla04cap-et01.png","category":"ARMOR","rarity":"uncommon","probability":0.01,"num":0},
	{"id":"12504","name":"Seakissed Marinva Suit","icon":"fbla04upper-et01.png","category":"ARMOR","rarity":"uncommon","probability":0.01,"num":0},
	{"id":"12965","name":"Seakissed Marinva Gauntlets","icon":"fbla04hand-et01.png","category":"ARMOR","rarity":"uncommon","probability":0.01,"num":0},
	{"id":"12727","name":"Seakissed Marinva Boots","icon":"fbla04foot-et01.png","category":"ARMOR","rarity":"uncommon","probability":0.01,"num":0},
	{"id":"17894","name":"Sealith Helmet","icon":"mele04cap-et01.png","category":"ARMOR","rarity":"common","probability":0.01,"num":0},
	{"id":"13044","name":"Sealith Suit","icon":"mele04upper-et01.png","category":"ARMOR","rarity":"common","probability":0.01,"num":0},
	{"id":"12806","name":"Sealith Gauntlets","icon":"mele04hand-et01.png","category":"ARMOR","rarity":"common","probability":0.01,"num":0},
	{"id":"14625","name":"Sealith Boots","icon":"mele04foot-et01.png","category":"ARMOR","rarity":"common","probability":0.01,"num":0},
	{"id":"15564","name":"Seavara Helmet","icon":"fele04cap-et01.png","category":"ARMOR","rarity":"common","probability":0.01,"num":0},
	{"id":"16299","name":"Seavara Suit","icon":"fele04upper-et01.png","category":"ARMOR","rarity":"common","probability":0.01,"num":0},
	{"id":"13773","name":"Seavara Gauntlets","icon":"fele04hand-et01.png","category":"ARMOR","rarity":"common","probability":0.01,"num":0},
	{"id":"10323","name":"Seavara Boots","icon":"fele04foot-et01.png","category":"ARMOR","rarity":"common","probability":0.01,"num":0},
	{"id":"12689","name":"Seakissed Sealith Helmet","icon":"mele04cap-et01.png","category":"ARMOR","rarity":"uncommon","probability":0.01,"num":0},
	{"id":"11104","name":"Seakissed Sealith Suit","icon":"mele04upper-et01.png","category":"ARMOR","rarity":"uncommon","probability":0.01,"num":0},
	{"id":"19321","name":"Seakissed Sealith Gauntlets","icon":"mele04hand-et01.png","category":"ARMOR","rarity":"uncommon","probability":0.01,"num":0},
	{"id":"12922","name":"Seakissed Sealith Boots","icon":"mele04foot-et01.png","category":"ARMOR","rarity":"uncommon","probability":0.01,"num":0},
	{"id":"14118","name":"Seakissed Seavara Helmet","icon":"fele04cap-et01.png","category":"ARMOR","rarity":"uncommon","probability":0.01,"num":0},
	{"id":"1324","name":"Seakissed Seavara Suit","icon":"fele04upper-et01.png","category":"ARMOR","rarity":"uncommon","probability":0.01,"num":0},
	{"id":"15423","name":"Seakissed Seavara Gauntlets","icon":"fele04hand-et01.png","category":"ARMOR","rarity":"uncommon","probability":0.01,"num":0},
	{"id":"11628","name":"Seakissed Seavara Boots","icon":"fele04foot-et01.png","category":"ARMOR","rarity":"uncommon","probability":0.01,"num":0},
	{"id":"13664","name":"Brinex Helmet","icon":"mjst04cap-et01.png","category":"ARMOR","rarity":"common","probability":0.01,"num":0},
	{"id":"17239","name":"Brinex Suit","icon":"mjst04upper-et01.png","category":"ARMOR","rarity":"common","probability":0.01,"num":0},
	{"id":"10840","name":"Brinex Gauntlets","icon":"mjst04hand-et01.png","category":"ARMOR","rarity":"common","probability":0.01,"num":0},
	{"id":"13248","name":"Brinex Boots","icon":"mjst04foot-et01.png","category":"ARMOR","rarity":"common","probability":0.01,"num":0},
	{"id":"14423","name":"Brineya Helmet","icon":"fjst04cap-et01.png","category":"ARMOR","rarity":"common","probability":0.01,"num":0},
	{"id":"19853","name":"Brineya Suit","icon":"fjst04upper-et01.png","category":"ARMOR","rarity":"common","probability":0.01,"num":0},
	{"id":"12587","name":"Brineya Gauntlets","icon":"fjst04hand-et01.png","category":"ARMOR","rarity":"common","probability":0.01,"num":0},
	{"id":"16643","name":"Brineya Boots","icon":"fjst04foot-et01.png","category":"ARMOR","rarity":"common","probability":0.01,"num":0},
	{"id":"14169","name":"Seakissed Brinex Helmet","icon":"mjst04cap-et01.png","category":"ARMOR","rarity":"uncommon","probability":0.01,"num":0},
	{"id":"12358","name":"Seakissed Brinex Suit","icon":"mjst04upper-et01.png","category":"ARMOR","rarity":"uncommon","probability":0.01,"num":0},
	{"id":"10814","name":"Seakissed Brinex Gauntlets","icon":"mjst04hand-et01.png","category":"ARMOR","rarity":"uncommon","probability":0.01,"num":0},
	{"id":"12195","name":"Seakissed Brinex Boots","icon":"mjst04foot-et01.png","category":"ARMOR","rarity":"uncommon","probability":0.01,"num":0},
	{"id":"14561","name":"Seakissed Brineya Helmet","icon":"fjst04cap-et01.png","category":"ARMOR","rarity":"uncommon","probability":0.01,"num":0},
	{"id":"19207","name":"Seakissed Brineya Suit","icon":"fjst04upper-et01.png","category":"ARMOR","rarity":"uncommon","probability":0.01,"num":0},
	{"id":"11773","name":"Seakissed Brineya Gauntlets","icon":"fjst04hand-et01.png","category":"ARMOR","rarity":"uncommon","probability":0.01,"num":0},
	{"id":"13394","name":"Seakissed Brineya Boots","icon":"fjst04foot-et01.png","category":"ARMOR","rarity":"uncommon","probability":0.01,"num":0},
	{"id":"10559","name":"Tidewhis Helmet","icon":"mkin04cap-et01.png","category":"ARMOR","rarity":"common","probability":0.01,"num":0},
	{"id":"10397","name":"Tidewhis Suit","icon":"mkin04upper-et01.png","category":"ARMOR","rarity":"common","probability":0.01,"num":0},
	{"id":"14318","name":"Tidewhis Gauntlets","icon":"mkin04hand-et01.png","category":"ARMOR","rarity":"common","probability":0.01,"num":0},
	{"id":"17087","name":"Tidewhis Boots","icon":"mkin04foot-et01.png","category":"ARMOR","rarity":"common","probability":0.01,"num":0},
	{"id":"11295","name":"Tidera Helmet","icon":"fkin04cap-et01.png","category":"ARMOR","rarity":"common","probability":0.01,"num":0},
	{"id":"16101","name":"Tidera Suit","icon":"fkin04upper-et01.png","category":"ARMOR","rarity":"common","probability":0.01,"num":0},
	{"id":"18078","name":"Tidera Gauntlets","icon":"fkin04hand-et01.png","category":"ARMOR","rarity":"common","probability":0.01,"num":0},
	{"id":"14617","name":"Tidera Boots","icon":"fkin04foot-et01.png","category":"ARMOR","rarity":"common","probability":0.01,"num":0},
	{"id":"11697","name":"Seakissed Tidewhis Helmet","icon":"mkin04cap-et01.png","category":"ARMOR","rarity":"uncommon","probability":0.01,"num":0},
	{"id":"6901","name":"Seakissed Tidewhis Suit","icon":"mkin04upper-et01.png","category":"ARMOR","rarity":"uncommon","probability":0.01,"num":0},
	{"id":"15319","name":"Seakissed Tidewhis Gauntlets","icon":"mkin04hand-et01.png","category":"ARMOR","rarity":"uncommon","probability":0.01,"num":0},
	{"id":"11751","name":"Seakissed Tidewhis Boots","icon":"mkin04foot-et01.png","category":"ARMOR","rarity":"uncommon","probability":0.01,"num":0},
	{"id":"11195","name":"Seakissed Tidera Helmet","icon":"fkin04cap-et01.png","category":"ARMOR","rarity":"uncommon","probability":0.01,"num":0},
	{"id":"16321","name":"Seakissed Tidera Suit","icon":"fkin04upper-et01.png","category":"ARMOR","rarity":"uncommon","probability":0.01,"num":0},
	{"id":"17121","name":"Seakissed Tidera Gauntlets","icon":"fkin04hand-et01.png","category":"ARMOR","rarity":"uncommon","probability":0.01,"num":0},
	{"id":"11114","name":"Seakissed Tidera Boots","icon":"fkin04foot-et01.png","category":"ARMOR","rarity":"uncommon","probability":0.01,"num":0},
	{"id":"16353","name":"Aquiloop Helmet","icon":"mpsy04cap-et01.png","category":"ARMOR","rarity":"common","probability":0.01,"num":0},
	{"id":"19979","name":"Aquiloop Suit","icon":"mpsy04upper-et01.png","category":"ARMOR","rarity":"common","probability":0.01,"num":0},
	{"id":"10845","name":"Aquiloop Gauntlets","icon":"mpsy04hand-et01.png","category":"ARMOR","rarity":"common","probability":0.01,"num":0},
	{"id":"12367","name":"Aquiloop Boots","icon":"mpsy04foot-et01.png","category":"ARMOR","rarity":"common","probability":0.01,"num":0},
	{"id":"15808","name":"Aquiva Helmet","icon":"fpsy04cap-et01.png","category":"ARMOR","rarity":"common","probability":0.01,"num":0},
	{"id":"14249","name":"Aquiva Suit","icon":"fpsy04upper-et01.png","category":"ARMOR","rarity":"common","probability":0.01,"num":0},
	{"id":"19157","name":"Aquiva Gauntlets","icon":"fpsy04hand-et01.png","category":"ARMOR","rarity":"common","probability":0.01,"num":0},
	{"id":"16645","name":"Aquiva Boots","icon":"fpsy04foot-et01.png","category":"ARMOR","rarity":"common","probability":0.01,"num":0},
	{"id":"14120","name":"Seakissed Aquiloop Helmet","icon":"mpsy04cap-et01.png","category":"ARMOR","rarity":"uncommon","probability":0.01,"num":0},
	{"id":"14185","name":"Seakissed Aquiloop Suit","icon":"mpsy04upper-et01.png","category":"ARMOR","rarity":"uncommon","probability":0.01,"num":0},
	{"id":"17542","name":"Seakissed Aquiloop Gauntlets","icon":"mpsy04hand-et01.png","category":"ARMOR","rarity":"uncommon","probability":0.01,"num":0},
	{"id":"18373","name":"Seakissed Aquiloop Boots","icon":"mpsy04foot-et01.png","category":"ARMOR","rarity":"uncommon","probability":0.01,"num":0},
	{"id":"13847","name":"Seakissed Aquiva Helmet","icon":"fpsy04cap-et01.png","category":"ARMOR","rarity":"uncommon","probability":0.01,"num":0},
	{"id":"18740","name":"Seakissed Aquiva Suit","icon":"fpsy04upper-et01.png","category":"ARMOR","rarity":"uncommon","probability":0.01,"num":0},
	{"id":"19089","name":"Seakissed Aquiva Gauntlets","icon":"fpsy04hand-et01.png","category":"ARMOR","rarity":"uncommon","probability":0.01,"num":0},
	{"id":"14390","name":"Seakissed Aquiva Boots","icon":"fpsy04foot-et01.png","category":"ARMOR","rarity":"uncommon","probability":0.01,"num":0},
	{"id":"10434","name":"Seerel Helmet","icon":"mrag04cap-et01.png","category":"ARMOR","rarity":"common","probability":0.01,"num":0},
	{"id":"14738","name":"Seerel Suit","icon":"mrag04upper-et01.png","category":"ARMOR","rarity":"common","probability":0.01,"num":0},
	{"id":"15719","name":"Seerel Gauntlets","icon":"mrag04hand-et01.png","category":"ARMOR","rarity":"common","probability":0.01,"num":0},
	{"id":"13948","name":"Seerel Boots","icon":"mrag04foot-et01.png","category":"ARMOR","rarity":"common","probability":0.01,"num":0},
	{"id":"10671","name":"Seerina Helmet","icon":"frag04cap-et01.png","category":"ARMOR","rarity":"common","probability":0.01,"num":0},
	{"id":"17096","name":"Seerina Suit","icon":"frag04upper-et01.png","category":"ARMOR","rarity":"common","probability":0.01,"num":0},
	{"id":"14241","name":"Seerina Gauntlets","icon":"frag04hand-et01.png","category":"ARMOR","rarity":"common","probability":0.01,"num":0},
	{"id":"13252","name":"Seerina Boots","icon":"frag04foot-et01.png","category":"ARMOR","rarity":"common","probability":0.01,"num":0},
	{"id":"19759","name":"Seakissed Seerel Helmet","icon":"mrag04cap-et01.png","category":"ARMOR","rarity":"uncommon","probability":0.01,"num":0},
	{"id":"12536","name":"Seakissed Seerel Suit","icon":"mrag04upper-et01.png","category":"ARMOR","rarity":"uncommon","probability":0.01,"num":0},
	{"id":"19056","name":"Seakissed Seerel Gauntlets","icon":"mrag04hand-et01.png","category":"ARMOR","rarity":"uncommon","probability":0.01,"num":0},
	{"id":"17761","name":"Seakissed Seerel Boots","icon":"mrag04foot-et01.png","category":"ARMOR","rarity":"uncommon","probability":0.01,"num":0},
	{"id":"13926","name":"Seakissed Seerina Helmet","icon":"frag04cap-et01.png","category":"ARMOR","rarity":"uncommon","probability":0.01,"num":0},
	{"id":"11186","name":"Seakissed Seerina Suit","icon":"frag04upper-et01.png","category":"ARMOR","rarity":"uncommon","probability":0.01,"num":0},
	{"id":"14325","name":"Seakissed Seerina Gauntlets","icon":"frag04hand-et01.png","category":"ARMOR","rarity":"uncommon","probability":0.01,"num":0},
	{"id":"18888","name":"Seakissed Seerina Boots","icon":"frag04foot-et01.png","category":"ARMOR","rarity":"uncommon","probability":0.01,"num":0},
	{"id":"16959","name":"Marinfury Helmet","icon":"mrin04cap-et01.png","category":"ARMOR","rarity":"common","probability":0.01,"num":0},
	{"id":"17559","name":"Marinfury Suit","icon":"mrin04upper-et01.png","category":"ARMOR","rarity":"common","probability":0.01,"num":0},
	{"id":"15658","name":"Marinfury Gauntlets","icon":"mrin04hand-et01.png","category":"ARMOR","rarity":"common","probability":0.01,"num":0},
	{"id":"12862","name":"Marinfury Boots","icon":"mrin04foot-et01.png","category":"ARMOR","rarity":"common","probability":0.01,"num":0},
	{"id":"17796","name":"Marinflux Helmet","icon":"frin04cap-et01.png","category":"ARMOR","rarity":"common","probability":0.01,"num":0},
	{"id":"18223","name":"Marinflux Suit","icon":"frin04upper-et01.png","category":"ARMOR","rarity":"common","probability":0.01,"num":0},
	{"id":"17124","name":"Marinflux Gauntlets","icon":"frin04hand-et01.png","category":"ARMOR","rarity":"common","probability":0.01,"num":0},
	{"id":"14983","name":"Marinflux Boots","icon":"frin04foot-et01.png","category":"ARMOR","rarity":"common","probability":0.01,"num":0},
	{"id":"16577","name":"Seakissed Marinfury Helmet","icon":"mrin04cap-et01.png","category":"ARMOR","rarity":"uncommon","probability":0.01,"num":0},
	{"id":"18567","name":"Seakissed Marinfury Suit","icon":"mrin04upper-et01.png","category":"ARMOR","rarity":"uncommon","probability":0.01,"num":0},
	{"id":"18504","name":"Seakissed Marinfury Gauntlets","icon":"mrin04hand-et01.png","category":"ARMOR","rarity":"uncommon","probability":0.01,"num":0},
	{"id":"17795","name":"Seakissed Marinfury Boots","icon":"mrin04foot-et01.png","category":"ARMOR","rarity":"uncommon","probability":0.01,"num":0},
	{"id":"19717","name":"Seakissed Marinflux Helmet","icon":"frin04cap-et01.png","category":"ARMOR","rarity":"uncommon","probability":0.01,"num":0},
	{"id":"16184","name":"Seakissed Marinflux Suit","icon":"frin04upper-et01.png","category":"ARMOR","rarity":"uncommon","probability":0.01,"num":0},
	{"id":"13067","name":"Seakissed Marinflux Gauntlets","icon":"frin04hand-et01.png","category":"ARMOR","rarity":"uncommon","probability":0.01,"num":0},
	{"id":"15280","name":"Seakissed Marinflux Boots","icon":"frin04foot-et01.png","category":"ARMOR","rarity":"uncommon","probability":0.01,"num":0},
	{"id":"16433","name":"Destroyed Coral Shield","icon":"armshihernes-et02.png","category":"ARMOR","rarity":"common","probability":0.01,"num":0},
	{"id":"12651","name":"Mossy Coral Shield","icon":"armshihernes-et01.png","category":"ARMOR","rarity":"uncommon","probability":0.01,"num":0},
	{"id":"107","name":"火属性装备卡片(2%)","icon":"genmateleflame.png","category":"MATERIAL","rarity":"common","probability":0.01,"num":0},
	{"id":"1159","name":"水属性装备卡片(2%)","icon":"genmateleriver.png","category":"MATERIAL","rarity":"common","probability":0.01,"num":0},
	{"id":"14","name":"风属性装备卡片(2%)","icon":"genmatelecyclon.png","category":"MATERIAL","rarity":"common","probability":0.01,"num":0},
	{"id":"7559","name":"雷属性装备卡片(2%)","icon":"genmatelegenerator.png","category":"MATERIAL","rarity":"common","probability":0.01,"num":0},
	{"id":"8926","name":"土属性装备卡片(2%)","icon":"genmateledesert.png","category":"MATERIAL","rarity":"common","probability":0.01,"num":0},
	{"id":"6803","name":"生命女神项链","icon":"genjewnecnornec01.png","category":"JEWELRY","rarity":"uncommon","probability":0.01,"num":0},
	{"id":"8646","name":"活力之源项链","icon":"genjewnecnornec03.png","category":"JEWELRY","rarity":"uncommon","probability":0.01,"num":0},
	{"id":"9233","name":"魔力之源项链","icon":"genjewnecnornec02.png","category":"JEWELRY","rarity":"uncommon","probability":0.01,"num":0},
	{"id":"5536","name":"力量戒指","icon":"genjewrinnorrin01.png","category":"JEWELRY","rarity":"uncommon","probability":0.01,"num":0},
	{"id":"1764","name":"敏捷戒指","icon":"genjewrinnorrin03.png","category":"JEWELRY","rarity":"uncommon","probability":0.01,"num":0},
	{"id":"2064","name":"智力戒指","icon":"genjewrinnorrin02.png","category":"JEWELRY","rarity":"uncommon","probability":0.01,"num":0},
	{"id":"6531","name":"体质戒指","icon":"genjewrinnorrin04.png","category":"JEWELRY","rarity":"uncommon","probability":0.01,"num":0},
	{"id":"2517","name":"火焰卡片(A)","icon":"genmatelepiercard_r_fire.png","category":"MATERIAL","rarity":"veryrare","probability":0.001,"num":0},
	{"id":"8591","name":"流水卡片(A)","icon":"genmatelepiercard_r_water.png","category":"MATERIAL","rarity":"veryrare","probability":0.001,"num":0},
	{"id":"5964","name":"暴风卡片(A)","icon":"genmatelepiercard_r_wind.png","category":"MATERIAL","rarity":"veryrare","probability":0.001,"num":0},
	{"id":"3100","name":"雷电卡片(A)","icon":"genmatelepiercard_r_electric.png","category":"MATERIAL","rarity":"veryrare","probability":0.001,"num":0},
	{"id":"5666","name":"岩石卡片(A)","icon":"genmatelepiercard_r_land.png","category":"MATERIAL","rarity":"veryrare","probability":0.001,"num":0},
	{"id":"8814","name":"岩浆卡片(A)","icon":"genmatelepiercard_r_lava.png","category":"MATERIAL","rarity":"veryrare","probability":0.001,"num":0},
	{"id":"4565","name":"电伏卡片(A)","icon":"genmatelepiercard_r_volt.png","category":"MATERIAL","rarity":"veryrare","probability":0.001,"num":0},
	{"id":"1961","name":"荆棘卡片(A)","icon":"genmatelepiercard_12_thorn.png","category":"MATERIAL","rarity":"veryrare","probability":0.001,"num":0},
	{"id":"7207","name":"火焰卡片","icon":"genmatelefire.png","category":"MATERIAL","rarity":"common","probability":0.001,"num":0},
	{"id":"3687","name":"烈火卡片","icon":"genmatelefire.png","category":"MATERIAL","rarity":"common","probability":0.001,"num":0},
	{"id":"7659","name":"湖泊卡片","icon":"genmatelewater.png","category":"MATERIAL","rarity":"common","probability":0.001,"num":0},
	{"id":"3830","name":"河流卡片","icon":"genmatelewater.png","category":"MATERIAL","rarity":"common","probability":0.001,"num":0},
	{"id":"1371","name":"电磁卡片","icon":"genmateleeletri.png","category":"MATERIAL","rarity":"common","probability":0.001,"num":0},
	{"id":"5455","name":"闪电卡片","icon":"genmateleeletri.png","category":"MATERIAL","rarity":"common","probability":0.001,"num":0},
	{"id":"9399","name":"巨石卡片","icon":"genmateleearth.png","category":"MATERIAL","rarity":"common","probability":0.001,"num":0},
	{"id":"6385","name":"沙漠卡片","icon":"genmateleearth.png","category":"MATERIAL","rarity":"common","probability":0.001,"num":0},
	{"id":"2781","name":"大风卡片","icon":"genmatelewind.png","category":"MATERIAL","rarity":"common","probability":0.001,"num":0},
	{"id":"5049","name":"旋风卡片","icon":"genmatelewind.png","category":"MATERIAL","rarity":"common","probability":0.001,"num":0},
	{"id":"2811","name":"火属性装备卡片(3%) ","icon":"genmateleflame.png","category":"MATERIAL","rarity":"common","probability":0.001,"num":0},
	{"id":"6439","name":"水属性装备卡片(3%)","icon":"genmateleriver.png","category":"MATERIAL","rarity":"common","probability":0.001,"num":0},
	{"id":"5788","name":"风属性装备卡片(3%)","icon":"genmatelecyclon.png","category":"MATERIAL","rarity":"common","probability":0.001,"num":0},
	{"id":"5545","name":"雷属性装备卡片(3%)","icon":"genmatelegenerator.png","category":"MATERIAL","rarity":"common","probability":0.001,"num":0},
	{"id":"6242","name":"土属性装备卡片(3%)","icon":"genmateledesert.png","category":"MATERIAL","rarity":"common","probability":0.001,"num":0},
	{"id":"17539","name":"Tigressa Helmet","icon":"fbilwildsset01cap.png","category":"ARMOR","rarity":"veryrare","probability":0.0001,"num":0},
	{"id":"19906","name":"Tigressa Suit","icon":"fbilwildsset01upper.png","category":"ARMOR","rarity":"veryrare","probability":0.0001,"num":0},
	{"id":"13927","name":"Tigressa Gauntlets","icon":"fbilwildsset01hand.png","category":"ARMOR","rarity":"veryrare","probability":0.0001,"num":0},
	{"id":"18586","name":"Tigressa Boots","icon":"fbilwildsset01foot.png","category":"ARMOR","rarity":"veryrare","probability":0.0001,"num":0},
	{"id":"10517","name":"Tigraknar Helmet","icon":"mbilwildsset01cap.png","category":"ARMOR","rarity":"veryrare","probability":0.0001,"num":0},
	{"id":"17202","name":"Tigraknar Suit","icon":"mbilwildsset01upper.png","category":"ARMOR","rarity":"veryrare","probability":0.0001,"num":0},
	{"id":"18920","name":"Tigraknar Gauntlets","icon":"mbilwildsset01hand.png","category":"ARMOR","rarity":"veryrare","probability":0.0001,"num":0},
	{"id":"13438","name":"Tigraknar Boots","icon":"mbilwildsset01foot.png","category":"ARMOR","rarity":"veryrare","probability":0.0001,"num":0},
	{"id":"11786","name":"Lyceris Helmet","icon":"fblawildsset01cap.png","category":"ARMOR","rarity":"veryrare","probability":0.0001,"num":0},
	{"id":"18584","name":"Lyceris Suit","icon":"fblawildsset01upper.png","category":"ARMOR","rarity":"veryrare","probability":0.0001,"num":0},
	{"id":"15083","name":"Lyceris Gauntlets","icon":"fblawildsset01hand.png","category":"ARMOR","rarity":"veryrare","probability":0.0001,"num":0},
	{"id":"19360","name":"Lyceris Boots","icon":"fblawildsset01foot.png","category":"ARMOR","rarity":"veryrare","probability":0.0001,"num":0},
	{"id":"10930","name":"Lycanith Helmet","icon":"mblawildsset01cap.png","category":"ARMOR","rarity":"veryrare","probability":0.0001,"num":0},
	{"id":"13367","name":"Lycanith Suit","icon":"mblawildsset01upper.png","category":"ARMOR","rarity":"veryrare","probability":0.0001,"num":0},
	{"id":"11059","name":"Lycanith Gauntlets","icon":"mblawildsset01hand.png","category":"ARMOR","rarity":"veryrare","probability":0.0001,"num":0},
	{"id":"17359","name":"Lycanith Boots","icon":"mblawildsset01foot.png","category":"ARMOR","rarity":"veryrare","probability":0.0001,"num":0},
	{"id":"15608","name":"Drakoria Helmet","icon":"felewildsset01cap.png","category":"ARMOR","rarity":"veryrare","probability":0.0001,"num":0},
	{"id":"14598","name":"Drakoria Suit","icon":"felewildsset01upper.png","category":"ARMOR","rarity":"veryrare","probability":0.0001,"num":0},
	{"id":"11158","name":"Drakoria Gauntlets","icon":"felewildsset01hand.png","category":"ARMOR","rarity":"veryrare","probability":0.0001,"num":0},
	{"id":"17733","name":"Drakoria Boots","icon":"felewildsset01foot.png","category":"ARMOR","rarity":"veryrare","probability":0.0001,"num":0},
	{"id":"19660","name":"Drakorin Helmet","icon":"melewildsset01cap.png","category":"ARMOR","rarity":"veryrare","probability":0.0001,"num":0},
	{"id":"12328","name":"Drakorin Suit","icon":"melewildsset01upper.png","category":"ARMOR","rarity":"veryrare","probability":0.0001,"num":0},
	{"id":"17067","name":"Drakorin Gauntlets","icon":"melewildsset01hand.png","category":"ARMOR","rarity":"veryrare","probability":0.0001,"num":0},
	{"id":"16398","name":"Drakorin Boots","icon":"melewildsset01foot.png","category":"ARMOR","rarity":"veryrare","probability":0.0001,"num":0},
	{"id":"15712","name":"Fennia Helmet","icon":"fjstwildsset01cap.png","category":"ARMOR","rarity":"veryrare","probability":0.0001,"num":0},
	{"id":"13143","name":"Fennia Suit","icon":"fjstwildsset01upper.png","category":"ARMOR","rarity":"veryrare","probability":0.0001,"num":0},
	{"id":"19405","name":"Fennia Gauntlets","icon":"fjstwildsset01hand.png","category":"ARMOR","rarity":"veryrare","probability":0.0001,"num":0},
	{"id":"11258","name":"Fennia Boots","icon":"fjstwildsset01foot.png","category":"ARMOR","rarity":"veryrare","probability":0.0001,"num":0},
	{"id":"17152","name":"Fennith Helmet","icon":"mjstwildsset01cap.png","category":"ARMOR","rarity":"veryrare","probability":0.0001,"num":0},
	{"id":"15392","name":"Fennith Suit","icon":"mjstwildsset01upper.png","category":"ARMOR","rarity":"veryrare","probability":0.0001,"num":0},
	{"id":"19029","name":"Fennith Gauntlets","icon":"mjstwildsset01hand.png","category":"ARMOR","rarity":"veryrare","probability":0.0001,"num":0},
	{"id":"16535","name":"Fennith Boots","icon":"mjstwildsset01foot.png","category":"ARMOR","rarity":"veryrare","probability":0.0001,"num":0},
	{"id":"11833","name":"Manetress Helmet","icon":"fkinwildsset01cap.png","category":"ARMOR","rarity":"veryrare","probability":0.0001,"num":0},
	{"id":"14690","name":"Manetress Suit","icon":"fkinwildsset01upper.png","category":"ARMOR","rarity":"veryrare","probability":0.0001,"num":0},
	{"id":"15495","name":"Manetress Gauntlets","icon":"fkinwildsset01hand.png","category":"ARMOR","rarity":"veryrare","probability":0.0001,"num":0},
	{"id":"11699","name":"Manetress Boots","icon":"fkinwildsset01foot.png","category":"ARMOR","rarity":"veryrare","probability":0.0001,"num":0},
	{"id":"14953","name":"Manebound Helmet","icon":"mkinwildsset01cap.png","category":"ARMOR","rarity":"veryrare","probability":0.0001,"num":0},
	{"id":"10929","name":"Manebound Suit","icon":"mkinwildsset01upper.png","category":"ARMOR","rarity":"veryrare","probability":0.0001,"num":0},
	{"id":"10056","name":"Manebound Gauntlets","icon":"mkinwildsset01hand.png","category":"ARMOR","rarity":"veryrare","probability":0.0001,"num":0},
	{"id":"15271","name":"Manebound Boots","icon":"mkinwildsset01foot.png","category":"ARMOR","rarity":"veryrare","probability":0.0001,"num":0},
	{"id":"10065","name":"Primalix Helmet","icon":"fpsywildsset01cap.png","category":"ARMOR","rarity":"veryrare","probability":0.0001,"num":0},
	{"id":"11543","name":"Primalix Suit","icon":"fpsywildsset01upper.png","category":"ARMOR","rarity":"veryrare","probability":0.0001,"num":0},
	{"id":"12567","name":"Primalix Gauntlets","icon":"fpsywildsset01hand.png","category":"ARMOR","rarity":"veryrare","probability":0.0001,"num":0},
	{"id":"5136","name":"Primalix Boots","icon":"fpsywildsset01foot.png","category":"ARMOR","rarity":"veryrare","probability":0.0001,"num":0},
	{"id":"13300","name":"Primamind Helmet","icon":"mpsywildsset01cap.png","category":"ARMOR","rarity":"veryrare","probability":0.0001,"num":0},
	{"id":"12749","name":"Primamind Suit","icon":"mpsywildsset01upper.png","category":"ARMOR","rarity":"veryrare","probability":0.0001,"num":0},
	{"id":"17123","name":"Primamind Gauntlets","icon":"mpsywildsset01hand.png","category":"ARMOR","rarity":"veryrare","probability":0.0001,"num":0},
	{"id":"17648","name":"Primamind Boots","icon":"mpsywildsset01foot.png","category":"ARMOR","rarity":"veryrare","probability":0.0001,"num":0},
	{"id":"17997","name":"Wingwander Helmet","icon":"fragwildsset01cap.png","category":"ARMOR","rarity":"veryrare","probability":0.0001,"num":0},
	{"id":"17360","name":"Wingwander Suit","icon":"fragwildsset01upper.png","category":"ARMOR","rarity":"veryrare","probability":0.0001,"num":0},
	{"id":"19124","name":"Wingwander Gauntlets","icon":"fragwildsset01hand.png","category":"ARMOR","rarity":"veryrare","probability":0.0001,"num":0},
	{"id":"15602","name":"Wingwander Boots","icon":"fragwildsset01foot.png","category":"ARMOR","rarity":"veryrare","probability":0.0001,"num":0},
	{"id":"15338","name":"Wingwalker Helmet","icon":"mragwildsset01cap.png","category":"ARMOR","rarity":"veryrare","probability":0.0001,"num":0},
	{"id":"12466","name":"Wingwalker Suit","icon":"mragwildsset01upper.png","category":"ARMOR","rarity":"veryrare","probability":0.0001,"num":0},
	{"id":"18400","name":"Wingwalker Gauntlets","icon":"mragwildsset01hand.png","category":"ARMOR","rarity":"veryrare","probability":0.0001,"num":0},
	{"id":"18180","name":"Wingwalker Boots","icon":"mragwildsset01foot.png","category":"ARMOR","rarity":"veryrare","probability":0.0001,"num":0},
	{"id":"18121","name":"Luminia Helmet","icon":"frinwildsset01cap.png","category":"ARMOR","rarity":"veryrare","probability":0.0001,"num":0},
	{"id":"18509","name":"Luminia Suit","icon":"frinwildsset01upper.png","category":"ARMOR","rarity":"veryrare","probability":0.0001,"num":0},
	{"id":"16265","name":"Luminia Gauntlets","icon":"frinwildsset01hand.png","category":"ARMOR","rarity":"veryrare","probability":0.0001,"num":0},
	{"id":"17340","name":"Luminia Boots","icon":"frinwildsset01foot.png","category":"ARMOR","rarity":"veryrare","probability":0.0001,"num":0},
	{"id":"11886","name":"Luminis Helmet","icon":"mrinwildsset01cap.png","category":"ARMOR","rarity":"veryrare","probability":0.0001,"num":0},
	{"id":"13626","name":"Luminis Suit","icon":"mrinwildsset01upper.png","category":"ARMOR","rarity":"veryrare","probability":0.0001,"num":0},
	{"id":"14048","name":"Luminis Gauntlets","icon":"mrinwildsset01hand.png","category":"ARMOR","rarity":"veryrare","probability":0.0001,"num":0},
	{"id":"10865","name":"Luminis Boots","icon":"mrinwildsset01foot.png","category":"ARMOR","rarity":"veryrare","probability":0.0001,"num":0},
	{"id":"16331","name":"卢萨卡之盾","icon":"armshilusika.png","category":"ARMOR","rarity":"veryrare","probability":0.0001,"num":0},
	{"id":"10209","name":"卢萨卡的水晶盾","icon":"armshicrylusika.png","category":"ARMOR","rarity":"veryrare","probability":0.0001,"num":0},
	{"id":"16721","name":"卢萨卡之斧","icon":"weaaxelusika.png","category":"WEAPON","rarity":"unique","probability":0.0001,"num":0},
	{"id":"15714","name":"卢萨卡的水晶斧","icon":"weaaxecrystal.png","category":"WEAPON","rarity":"unique","probability":0.0001,"num":0},
	{"id":"11095","name":"卢萨卡之弓","icon":"weabowlusika.png","category":"WEAPON","rarity":"unique","probability":0.0001,"num":0},
	{"id":"11905","name":"卢萨卡的水晶弓","icon":"weabowcrystal.png","category":"WEAPON","rarity":"unique","probability":0.0001,"num":0},
	{"id":"16135","name":"卢萨卡之拳","icon":"weaknulusika.png","category":"WEAPON","rarity":"unique","probability":0.0001,"num":0},
	{"id":"14100","name":"卢萨卡的水晶拳","icon":"weaknucrystal.png","category":"WEAPON","rarity":"unique","probability":0.0001,"num":0},
	{"id":"9319","name":"卢萨卡法杖","icon":"weastalusika.png","category":"WEAPON","rarity":"unique","probability":0.0001,"num":0},
	{"id":"17625","name":"卢萨卡的水晶法杖","icon":"weastacrystal.png","category":"WEAPON","rarity":"unique","probability":0.0001,"num":0},
	{"id":"15880","name":"卢萨卡魔棒","icon":"weachelusika.png","category":"WEAPON","rarity":"unique","probability":0.0001,"num":0},
	{"id":"18022","name":"卢萨卡的水晶魔棒","icon":"weachecrystal.png","category":"WEAPON","rarity":"unique","probability":0.0001,"num":0},
	{"id":"19508","name":"卢萨卡之剑","icon":"weaswolusika.png","category":"WEAPON","rarity":"unique","probability":0.0001,"num":0},
	{"id":"13556","name":"卢萨卡的水晶剑","icon":"weaswocrystal.png","category":"WEAPON","rarity":"unique","probability":0.0001,"num":0},
	{"id":"14844","name":"卢萨卡巨斧","icon":"weaaxtlusika.png","category":"WEAPON","rarity":"unique","probability":0.0001,"num":0},
	{"id":"17978","name":"卢萨卡的水晶巨斧","icon":"weaaxtcrystal.png","category":"WEAPON","rarity":"unique","probability":0.0001,"num":0},
	{"id":"18025","name":"卢萨卡巨剑","icon":"weaswtlusika.png","category":"WEAPON","rarity":"unique","probability":0.0001,"num":0},
	{"id":"16364","name":"卢萨卡的水晶巨剑","icon":"weaswtcrystal.png","category":"WEAPON","rarity":"unique","probability":0.0001,"num":0},
	{"id":"15677","name":"卢萨卡魔杖","icon":"weawanlusika.png","category":"WEAPON","rarity":"unique","probability":0.0001,"num":0},
	{"id":"19761","name":"卢萨卡的水晶魔杖","icon":"weawanrustiacrystal.png","category":"WEAPON","rarity":"unique","probability":0.0001,"num":0},
	{"id":"18619","name":"卢萨卡飞轮","icon":"weayoylusika.png","category":"WEAPON","rarity":"unique","probability":0.0001,"num":0},
	{"id":"15533","name":"卢萨卡的水晶飞轮","icon":"weayoycrystal.png","category":"WEAPON","rarity":"unique","probability":0.0001,"num":0},
	{"id":"4635","name":"火属性装备卡片(4%)","icon":"genmateleflame.png","category":"MATERIAL","rarity":"rare","probability":0.0001,"num":0},
	{"id":"4126","name":"水属性装备卡片(4%)","icon":"genmateleriver.png","category":"MATERIAL","rarity":"rare","probability":0.0001,"num":0},
	{"id":"5945","name":"风属性装备卡片(4%)","icon":"genmatelecyclon.png","category":"MATERIAL","rarity":"rare","probability":0.0001,"num":0},
	{"id":"8243","name":"雷属性装备卡片(4%)","icon":"genmatelegenerator.png","category":"MATERIAL","rarity":"rare","probability":0.0001,"num":0},
	{"id":"7436","name":"土属性装备卡片(4%)","icon":"genmateledesert.png","category":"MATERIAL","rarity":"rare","probability":0.0001,"num":0},
];